# ============================================================
# EQ36 build system
# Builds EQ3/6 v8.0a Fortran executables from the upstream ZIP
# stored in the git submodule at upstream/.
#
# Quick start:
#   make fetch    - initialize upstream submodule
#   make          - extract + build all executables
#   make docs     - download documentation PDFs to docs/
#
# Packaging:
#   make rpm      - build RPM (Linux, requires rpm-build)
#   make deb      - build .deb (Linux, requires dpkg-dev debhelper)
#   make brew     - install via Homebrew formula
#
# Manual symlink install (LINK_DIR must be set explicitly):
#   make symlinks LINK_DIR=/usr/local/bin
# ============================================================

FC     = gfortran
# -std=legacy accepts old-style Fortran 77 FORMAT strings (missing commas
# between descriptors) that gfortran 15+ rejects at runtime by default.
FFLAGS = -O2 -std=legacy

# Bake in Fortran/GCC runtimes for self-contained, archivable binaries.
# glibc remains dynamic (ABI-stable across all target Linux versions).
LDFLAGS = -static-libgfortran -static-libgcc

# Upstream ZIP (provided by the git submodule)
UPSTREAM_ZIP       = upstream/EQ36_80a_Linux.zip
INNER_SRC_TAR      = Linux/EQ3_6v8.0a/archsrc.tar
INNER_DB_TAR       = Linux/EQ3_6v8.0a/archdb.tar
TESTLIB_PC_ZIP     = upstream/EQ3_6v8.0a\ TestLibrary\ PC.zip
TESTLIB_INPUTS     = tests/testlib/inputs
TESTLIB_EXPECTED   = tests/testlib/expected
DATA1_CACHE        = tests/.data1_cache
VERSION       = 8.0a
DEW_VERSION   = 3245r136

# Source extraction root (gitignored, regenerated by make extract)
SRC_BASE = src

# Build output directories
BIN_DIR = bin
OBJ_DIR = obj

# Stamp file so extraction only runs once (or when the ZIP changes)
EXTRACT_STAMP = $(SRC_BASE)/.extracted

# Documentation PDFs from OSTI (downloaded by make docs; gitignored)
DOCS_DIR       = docs
OSTI_BASE      = https://www.osti.gov/servlets/purl
DOC_138894     = $(DOCS_DIR)/138894.pdf   # Part 1: EQ3/6 overview and installation guide
DOC_138639     = $(DOCS_DIR)/138639.pdf   # Part 2: EQPT user's guide
DOC_138643     = $(DOCS_DIR)/138643.pdf   # Part 3: EQ3NR theoretical manual and user's guide
DOC_138820     = $(DOCS_DIR)/138820.pdf   # Part 4: EQ6 theoretical manual and user's guide
DOCS           = $(DOC_138894) $(DOC_138639) $(DOC_138643) $(DOC_138820)
DOCS_SHA256    = docs/SHA256SUMS

# Platform detection (used for packaging target warnings)
UNAME_S := $(shell uname -s)

# Debian/Ubuntu architecture token (e.g. amd64, arm64)
DEB_ARCH := $(shell dpkg --print-architecture 2>/dev/null || echo amd64)

# SHA256 verification command (sha256sum on Linux, shasum on macOS)
ifeq ($(UNAME_S),Darwin)
  SHA256_CHECK = shasum -a 256 -c
else
  SHA256_CHECK = sha256sum -c
endif

# ---- Source directories ----------------------------------------
EQLIBU_SRC_DIR = $(SRC_BASE)/eqlibu/src
EQLIBG_SRC_DIR = $(SRC_BASE)/eqlibg/src
EQLIB_SRC_DIR  = $(SRC_BASE)/eqlib/src
EQ3NR_SRC_DIR  = $(SRC_BASE)/eq3nr/src
EQ6_SRC_DIR    = $(SRC_BASE)/eq6/src
EQPT_SRC_DIR   = $(SRC_BASE)/eqpt/src
XCON3_SRC_DIR  = $(SRC_BASE)/xcon3/src
XCON6_SRC_DIR  = $(SRC_BASE)/xcon6/src

# ---- Executables -----------------------------------------------
TARGETS = \
    $(BIN_DIR)/eq3nr \
    $(BIN_DIR)/eq6 \
    $(BIN_DIR)/eqpt \
    $(BIN_DIR)/xcon3 \
    $(BIN_DIR)/xcon6

# ---- Source file lists -----------------------------------------
# Basenames are defined in sources.mk (tracked); full paths are derived here.
# Update sources.mk with 'make regen-sources' after bumping the upstream submodule.
include sources.mk
EQLIBU_SRC     = $(addprefix $(EQLIBU_SRC_DIR)/, $(EQLIBU_SRCS))
EQLIBG_SRC     = $(addprefix $(EQLIBG_SRC_DIR)/, $(EQLIBG_SRCS))
EQLIB_SRC      = $(addprefix $(EQLIB_SRC_DIR)/,  $(EQLIB_SRCS))
EQ3NR_SRC      = $(addprefix $(EQ3NR_SRC_DIR)/,  $(EQ3NR_SRCS))
EQ6_MODULE_SRC = $(addprefix $(EQ6_SRC_DIR)/,    $(EQ6_MODULE_SRCS))
EQ6_OTHER_SRC  = $(addprefix $(EQ6_SRC_DIR)/,    $(EQ6_OTHER_SRCS))
EQPT_SRC       = $(addprefix $(EQPT_SRC_DIR)/,   $(EQPT_SRCS))
XCON3_SRC      = $(addprefix $(XCON3_SRC_DIR)/,  $(XCON3_SRCS))
XCON6_SRC      = $(addprefix $(XCON6_SRC_DIR)/,  $(XCON6_SRCS))

# ---- Object file lists -----------------------------------------
EQLIBU_OBJ     = $(EQLIBU_SRCS:%.f=$(OBJ_DIR)/%.o)
EQLIBG_OBJ     = $(EQLIBG_SRCS:%.f=$(OBJ_DIR)/%.o)
EQLIB_OBJ      = $(EQLIB_SRCS:%.f=$(OBJ_DIR)/%.o)
EQ3NR_OBJ      = $(EQ3NR_SRCS:%.f=$(OBJ_DIR)/%.o)
EQ6_MODULE_OBJ = $(EQ6_MODULE_SRCS:%.f=$(OBJ_DIR)/%.o)
EQ6_OTHER_OBJ  = $(EQ6_OTHER_SRCS:%.f=$(OBJ_DIR)/%.o)
EQ6_OBJ        = $(EQ6_MODULE_OBJ) $(EQ6_OTHER_OBJ)
EQPT_OBJ       = $(EQPT_SRCS:%.f=$(OBJ_DIR)/%.o)
XCON3_OBJ      = $(XCON3_SRCS:%.f=$(OBJ_DIR)/%.o)
XCON6_OBJ      = $(XCON6_SRCS:%.f=$(OBJ_DIR)/%.o)

# ============================================================
# DEFAULT TARGET
# ============================================================
.DEFAULT_GOAL := all

all: build

# CPU count for parallel compilation: nproc (Linux), sysctl (macOS), fallback 1.
NPROC := $(shell nproc 2>/dev/null || sysctl -n hw.logicalcpu 2>/dev/null || echo 1)

# ---- Farm build configuration ----------------------------------
# Builder hostnames live in ssh_build_farm.mk (gitignored, never committed).
# Copy ssh_build_farm.mk.example to ssh_build_farm.mk and fill in your hostnames.
-include ssh_build_farm.mk

# Per-platform farm connection strings and repo paths.
# Set in ssh_build_farm.mk.  Empty CONNECTION = run locally; 'ssh host' (or
# 'ssh host env PATH=...' for Mac) = run on a remote builder.
# FARM_REPO must be a path the remote shell can expand (absolute or tilde).
FEDORA_CONNECTION ?=
UBUNTU_CONNECTION ?=
MAC_CONNECTION    ?=
FEDORA_FARM_REPO  ?=
UBUNTU_FARM_REPO  ?=
MAC_FARM_REPO     ?=

# Remote URLs — default to HTTPS so builds work on machines without SSH keys.
# Override in ssh_build_farm.mk to use SSH on builders that have keys configured.
REPO_URL         ?= https://github.com/jonnyprouty/EQ3_6-dist.git
UPSTREAM_URL     ?= https://github.com/llnl/EQ3_6
UPSTREAM_DEW_URL ?= https://gitlab.com/ENKI-portal/SUPCRTandEQs.git

# Two-phase build: extraction first, then a fresh $(MAKE) invocation for
# compilation.  The sub-make ensures src/ is fully populated before any
# compile rules fire, regardless of how make schedules prerequisites.
build: $(EXTRACT_STAMP)
	@$(MAKE) --no-print-directory -j$(NPROC) $(TARGETS)

# ============================================================
# FETCH: initialize / update the upstream git submodule
# ============================================================
fetch:
	git submodule init upstream
	git config submodule.upstream.url "$(UPSTREAM_URL)"
	git submodule update upstream

# Auto-fetch rule: fires when make tries to build a target that needs an
# upstream ZIP but the submodule hasn't been initialized yet.  Both ZIPs live
# inside upstream/, so initializing the submodule provides both.
$(UPSTREAM_ZIP) $(TESTLIB_PC_ZIP):
	@echo "==> upstream submodule not initialized — running make fetch ..."
	git submodule init upstream
	git config submodule.upstream.url "$(UPSTREAM_URL)"
	git submodule update upstream

# ============================================================
# EXTRACT: unpack source from upstream ZIP, then decompress
#
# archsrc.tar stores every .f and .h (and .k) file as .f.gz /
# .h.gz / .k.gz.  gfortran cannot compile compressed files, so
# gunzip is mandatory before compilation.
#
# Uses 'xargs gunzip' rather than 'gunzip -r' for macOS compat
# (BSD gunzip on macOS does not support the -r flag).
# ============================================================
$(EXTRACT_STAMP): $(UPSTREAM_ZIP)
	@echo "==> Extracting Fortran sources from $(UPSTREAM_ZIP) ..."
	@mkdir -p $(SRC_BASE)
	unzip -p $(UPSTREAM_ZIP) $(INNER_SRC_TAR) | tar -xf - -C $(SRC_BASE)/
	@echo "==> Decompressing .gz source files ..."
	find $(SRC_BASE) -name '*.gz' | xargs gunzip
	@touch $@
	@echo "==> Extraction complete."

extract: $(EXTRACT_STAMP)

# ============================================================
# DOCS: download documentation PDFs from OSTI
# ============================================================
# Individual PDF rules — each verifies its SHA256 after download.
# If verification fails, the partial file is removed and make aborts.
$(DOC_138894):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138894
	cd $(DOCS_DIR) && grep 138894.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

$(DOC_138639):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138639
	cd $(DOCS_DIR) && grep 138639.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

$(DOC_138643):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138643
	cd $(DOCS_DIR) && grep 138643.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

$(DOC_138820):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138820
	cd $(DOCS_DIR) && grep 138820.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

docs: $(DOCS)

# ============================================================
# COMPILATION: pattern rules
#
# -J$(OBJ_DIR) tells gfortran to write .mod files to obj/ and
# to search obj/ when resolving USE statements.
#
# Include paths (e.g. '../../eqlib/inc/eqldef.h') are relative
# to the source file's location — gfortran resolves them from
# the source directory, so no -I flags are needed.
#
# All 496 source basenames are globally unique across the 8
# component directories, so a single flat obj/ is safe.
# ============================================================
$(OBJ_DIR)/%.o: $(EQLIBU_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQLIBG_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQLIB_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQ3NR_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

# EQ6 module files — explicit targets, no extra prerequisites
$(OBJ_DIR)/mod6pt.o: $(EQ6_SRC_DIR)/mod6pt.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/mod6xf.o: $(EQ6_SRC_DIR)/mod6xf.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

# Non-module EQ6 files: order-only dep ensures modules are compiled first
$(EQ6_OTHER_OBJ): | $(EQ6_MODULE_OBJ)

$(OBJ_DIR)/%.o: $(EQ6_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQPT_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(XCON3_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(XCON6_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

# ============================================================
# LINK: build executables
# ============================================================
$(BIN_DIR)/eq3nr: $(EQLIBU_OBJ) $(EQLIBG_OBJ) $(EQLIB_OBJ) $(EQ3NR_OBJ)
	$(FC) $(FFLAGS) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/eq6: $(EQLIBU_OBJ) $(EQLIBG_OBJ) $(EQLIB_OBJ) $(EQ6_OBJ)
	$(FC) $(FFLAGS) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/eqpt: $(EQLIBU_OBJ) $(EQPT_OBJ)
	$(FC) $(FFLAGS) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/xcon3: $(EQLIBU_OBJ) $(XCON3_OBJ)
	$(FC) $(FFLAGS) $(LDFLAGS) -o $@ $^

$(BIN_DIR)/xcon6: $(EQLIBU_OBJ) $(XCON6_OBJ)
	$(FC) $(FFLAGS) $(LDFLAGS) -o $@ $^

# ============================================================
# DEW VARIANT: SUPCRTandEQs/DEW_activities, gfortran build
#
# Independent variant of EQ3/6 modified for high P-T DEW conditions.
# Built from https://gitlab.com/ENKI-portal/SUPCRTandEQs (DEW_activities branch).
# Executables land in bin-dew/; does not conflict with v8.0a bin/.
#
# Quick start:
#   make fetch-dew   - initialize upstream-dew submodule
#   make build-dew   - compile all DEW executables to bin-dew/
#   make test-dew    - run DEW smoke tests (skipped if bin-dew/ absent)
# ============================================================

DEW_UPSTREAM     = upstream-dew
DEW_BIN_DIR      = bin-dew
DEW_OBJ_DIR      = obj-dew

# Include paths: root-level .h files + each subdir's own .h files.
# -ffixed-line-length-none: the DEW source has lines > 72 chars (written for f2c);
# standard F77 would silently truncate them, breaking format strings.
# These three flags together eliminate non-determinism in the DEW R110/R100
# executables, which contain numerous uninitialized Fortran variables:
#
#   -finit-character=32   CHARACTER variables → spaces (ASCII 32).
#     Needed because eqpt writes uninitialized CHARACTER buffers into the
#     binary data1/data2/data3 files, and eq3/eq6 use uninitialized CHARACTER
#     variables in species-name comparisons that alter convergence paths.
#
#   -finit-real=zero      REAL variables → 0.0.
#     Without this, uninitialized REAL locals perturb the EQ6 ODE
#     predictor-corrector, causing last-digit pH/concentration differences
#     across process invocations on the same platform.
#
#   -finit-integer=0      INTEGER variables → 0.
#     Defensive: prevents uninitialized INTEGER flags from taking invalid
#     values that could misdirect activity-model or convergence logic.
#
# The betgam subroutine in eqlibr136.f has a related bug (missing eqlgp.h
# include — see patches/dew-eqlibr136-betgam-eqlgp.patch) that would trigger
# a fatal error when -finit-character=32 is applied without that fix.
DEW_FFLAGS = $(FFLAGS) -ffixed-line-length-none \
    -finit-character=32 -finit-real=zero -finit-integer=0 \
    -I$(DEW_UPSTREAM) \
    -I$(DEW_UPSTREAM)/EQPT \
    -I$(DEW_UPSTREAM)/EQ3 \
    -I$(DEW_UPSTREAM)/EQ6 \
    -I$(DEW_UPSTREAM)/SUPCRT \
    -I$(DEW_UPSTREAM)/CPRONS

# eqpt uses the same flags as the rest; the single DEW_FFLAGS covers all five
# DEW executables uniformly.
DEW_EQPT_FFLAGS = $(DEW_FFLAGS)

# Source files
DEW_EQLIB_SRC      = $(DEW_UPSTREAM)/eqlibr136.f
DEW_EQPT_SRC       = $(DEW_UPSTREAM)/EQPT/eqpt.f
DEW_EQ3_SRC        = $(DEW_UPSTREAM)/EQ3/eq3nr110.f
DEW_EQ6_SRC        = $(DEW_UPSTREAM)/EQ6/eq6r100.f
DEW_SUPCRT_SRC_DIR = $(DEW_UPSTREAM)/SUPCRT
DEW_CPRONS_SRC_DIR = $(DEW_UPSTREAM)/CPRONS

# Object files
DEW_EQLIB_OBJ  = $(DEW_OBJ_DIR)/eqlibr136.o
DEW_EQPT_OBJ   = $(DEW_OBJ_DIR)/eqpt_dew.o
DEW_EQ3_OBJ    = $(DEW_OBJ_DIR)/eq3nr110.o
DEW_EQ6_OBJ    = $(DEW_OBJ_DIR)/eq6r100.o
DEW_SUPCRT_OBJ = \
    $(DEW_OBJ_DIR)/sup92pc.o \
    $(DEW_OBJ_DIR)/reac92pc.o \
    $(DEW_OBJ_DIR)/rep92pc.o \
    $(DEW_OBJ_DIR)/H2O92D.o
DEW_CPRONS_OBJ = $(DEW_OBJ_DIR)/cprons92.o

DEW_EQLIB_A = $(DEW_OBJ_DIR)/libeq_dew.a

# Patches to apply before compiling DEW sources.
# Each patch is a unified diff relative to the repo root (patch -p1).
# Re-applied when any patch file changes or the submodule is updated.
DEW_PATCHES     = $(sort $(wildcard patches/dew-*.patch))
DEW_PATCH_STAMP = $(DEW_OBJ_DIR)/.patches-applied

DEW_TARGETS = \
    $(DEW_BIN_DIR)/eqpt \
    $(DEW_BIN_DIR)/eq3 \
    $(DEW_BIN_DIR)/eq6 \
    $(DEW_BIN_DIR)/supcrt \
    $(DEW_BIN_DIR)/cprons92

# ---- DEW fetch -----------------------------------------------
fetch-dew:
	git submodule init upstream-dew
	git config submodule.upstream-dew.url "$(UPSTREAM_DEW_URL)"
	git submodule update upstream-dew

# Auto-fetch rule: fires when make tries to build a DEW target but the
# submodule hasn't been initialized yet.  The DEW patch stamp depends on this
# file to detect when the submodule is updated to a new commit.
.git/modules/upstream-dew/HEAD:
	@echo "==> upstream-dew submodule not initialized — running make fetch-dew ..."
	git submodule init upstream-dew
	git config submodule.upstream-dew.url "$(UPSTREAM_DEW_URL)"
	git submodule update upstream-dew

# ---- DEW patch precompile hook --------------------------------
# Applies all patches/dew-*.patch to upstream-dew/ before compilation.
# patch -N skips hunks that are already applied; || true absorbs the
# non-zero exit so the stamp is always touched on success.
# Re-runs when any patch changes or the submodule is updated.
patch-dew: $(DEW_PATCH_STAMP)

$(DEW_PATCH_STAMP): $(DEW_PATCHES) .git/modules/upstream-dew/HEAD | $(DEW_OBJ_DIR)
	@if [ -n "$(DEW_PATCHES)" ]; then \
	    echo "==> Applying DEW source patches ..."; \
	    for p in $(DEW_PATCHES); do \
	        echo "    $$p"; \
	        patch -p1 -N --batch --reject-file=/dev/null < "$$p" >/dev/null 2>&1 || true; \
	    done; \
	fi
	@touch $@

# ---- DEW build -----------------------------------------------
build-dew: $(DEW_TARGETS)

$(DEW_OBJ_DIR) $(DEW_BIN_DIR):
	mkdir -p $@

# Shared EQ library — static archive for clean linking
$(DEW_EQLIB_OBJ): $(DEW_EQLIB_SRC) $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_EQLIB_A): $(DEW_EQLIB_OBJ)
	ar rcs $@ $^

# EQPT (DATA0→data1 preprocessor)
$(DEW_EQPT_OBJ): $(DEW_EQPT_SRC) $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_EQPT_FFLAGS) -c $< -o $@

$(DEW_BIN_DIR)/eqpt: $(DEW_EQPT_OBJ) $(DEW_EQLIB_A) | $(DEW_BIN_DIR)
	$(FC) $(LDFLAGS) -o $@ $^

# EQ3 speciation (R110)
$(DEW_EQ3_OBJ): $(DEW_EQ3_SRC) $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_BIN_DIR)/eq3: $(DEW_EQ3_OBJ) $(DEW_EQLIB_A) | $(DEW_BIN_DIR)
	$(FC) $(LDFLAGS) -o $@ $^

# EQ6 mass transfer (R100)
$(DEW_EQ6_OBJ): $(DEW_EQ6_SRC) $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_BIN_DIR)/eq6: $(DEW_EQ6_OBJ) $(DEW_EQLIB_A) | $(DEW_BIN_DIR)
	$(FC) $(LDFLAGS) -o $@ $^

# SUPCRT (thermodynamic property calculator; standalone, no eqlib)
$(DEW_OBJ_DIR)/sup92pc.o: $(DEW_SUPCRT_SRC_DIR)/sup92pc.f $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_OBJ_DIR)/reac92pc.o: $(DEW_SUPCRT_SRC_DIR)/reac92pc.f $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_OBJ_DIR)/rep92pc.o: $(DEW_SUPCRT_SRC_DIR)/rep92pc.f $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_OBJ_DIR)/H2O92D.o: $(DEW_SUPCRT_SRC_DIR)/H2O92D.f $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_BIN_DIR)/supcrt: $(DEW_SUPCRT_OBJ) | $(DEW_BIN_DIR)
	$(FC) $(LDFLAGS) -o $@ $^

# CPRONS (sprons sequential→direct access converter; standalone)
$(DEW_CPRONS_OBJ): $(DEW_CPRONS_SRC_DIR)/cprons92.f $(DEW_PATCH_STAMP) | $(DEW_OBJ_DIR)
	$(FC) $(DEW_FFLAGS) -c $< -o $@

$(DEW_BIN_DIR)/cprons92: $(DEW_CPRONS_OBJ) | $(DEW_BIN_DIR)
	$(FC) $(LDFLAGS) -o $@ $^

# ---- DEW test ------------------------------------------------
test-dew: $(DEW_TARGETS) $(DEW_WORKSHOP_STAMPS)
	@bats --recursive tests/cases/dew/

# ---- DEW clean -----------------------------------------------
clean-dew:
	rm -rf $(DEW_OBJ_DIR) $(DEW_BIN_DIR)
	git -C upstream-dew checkout -- . 2>/dev/null || true
	find upstream-dew \( -name '*.rej' -o -name '*.orig' \) -delete 2>/dev/null || true

# ============================================================
# SYMLINKS: install executables as symlinks in a user-specified directory.
# v8.0a: make symlinks LINK_DIR=~/.local/bin
# DEW:   make symlinks-dew LINK_DIR=~/.local/bin  (installs with dew- prefix)
# Both targets may point to the same LINK_DIR — no name conflicts.
# ============================================================
symlinks: _check-link-dir $(TARGETS)
	mkdir -p $(LINK_DIR)
	ln -sf $(CURDIR)/$(BIN_DIR)/eq3nr  $(LINK_DIR)/eq3nr
	ln -sf $(CURDIR)/$(BIN_DIR)/eq6    $(LINK_DIR)/eq6
	ln -sf $(CURDIR)/$(BIN_DIR)/eqpt   $(LINK_DIR)/eqpt
	ln -sf $(CURDIR)/$(BIN_DIR)/xcon3  $(LINK_DIR)/xcon3
	ln -sf $(CURDIR)/$(BIN_DIR)/xcon6  $(LINK_DIR)/xcon6
	@echo "Symlinks created in $(LINK_DIR)"

.PHONY: _check-link-dir
_check-link-dir:
ifndef LINK_DIR
	$(error LINK_DIR is not set. Usage: make symlinks LINK_DIR=/path/to/bin)
endif

# DEW variant symlinks — installed with dew- prefix so both variants
# coexist in the same LINK_DIR without collision.
symlinks-dew: _check-link-dir-dew $(DEW_TARGETS)
	mkdir -p $(LINK_DIR)
	ln -sf $(CURDIR)/$(DEW_BIN_DIR)/eqpt     $(LINK_DIR)/dew-eqpt
	ln -sf $(CURDIR)/$(DEW_BIN_DIR)/eq3      $(LINK_DIR)/dew-eq3
	ln -sf $(CURDIR)/$(DEW_BIN_DIR)/eq6      $(LINK_DIR)/dew-eq6
	ln -sf $(CURDIR)/$(DEW_BIN_DIR)/supcrt   $(LINK_DIR)/dew-supcrt
	ln -sf $(CURDIR)/$(DEW_BIN_DIR)/cprons92 $(LINK_DIR)/dew-cprons92
	@echo "DEW symlinks (dew-*) created in $(LINK_DIR)"

.PHONY: _check-link-dir-dew
_check-link-dir-dew:
ifndef LINK_DIR
	$(error LINK_DIR is not set. Usage: make symlinks-dew LINK_DIR=/path/to/bin)
endif

# ============================================================
# GENERATED FILES
# Packaging templates (*.in) processed by make via sed substitution.
# The *.in files are the authoritative sources to edit.
# Generated outputs are gitignored and always rebuilt from the template.
# ============================================================

pkg/rpm/eq3_6.spec: pkg/rpm/eq3_6.spec.in Makefile
	sed \
	    -e 's|@@VERSION@@|$(VERSION)|g' \
	    -e 's|@@FC@@|$(FC)|g' \
	    -e 's|@@FFLAGS@@|$(FFLAGS)|g' \
	    -e 's|@@LDFLAGS@@|$(LDFLAGS)|g' \
	    $< > $@

pkg/rpm/eq3_6_dew.spec: pkg/rpm/eq3_6_dew.spec.in Makefile
	sed \
	    -e 's|@@DEW_VERSION@@|$(DEW_VERSION)|g' \
	    -e 's|@@FC@@|$(FC)|g' \
	    -e 's|@@FFLAGS@@|$(FFLAGS)|g' \
	    -e 's|@@LDFLAGS@@|$(LDFLAGS)|g' \
	    $< > $@

pkg/brew/eq3_6.rb: pkg/brew/eq3_6.rb.in Makefile
	sed -e 's|@@FFLAGS@@|$(FFLAGS)|g' $< > $@

# DEW Homebrew formula: source tarball is created from the upstream-dew submodule
# so no remote download is needed.  sha256 is computed from the tarball at
# generation time and substituted along with the file:// URL.
DEW_SRC_TARBALL = pkg/brew/SUPCRTandEQs_DEW_activities.tar.gz

$(DEW_SRC_TARBALL): | $(DEW_UPSTREAM)
	git -C $(DEW_UPSTREAM) archive --prefix=SUPCRTandEQs/ HEAD \
	    | gzip > $@

pkg/brew/eq3_6_dew.rb: pkg/brew/eq3_6_dew.rb.in Makefile $(DEW_SRC_TARBALL)
	@DEW_SHA256=$$(sha256sum $(DEW_SRC_TARBALL) | cut -d' ' -f1); \
	DEW_URL="file://$(CURDIR)/$(DEW_SRC_TARBALL)"; \
	sed \
	    -e 's|@@FFLAGS@@|$(FFLAGS)|g' \
	    -e "s|@@DEW_SRC_URL@@|$$DEW_URL|g" \
	    -e "s|@@DEW_SHA256@@|$$DEW_SHA256|g" \
	    $< > $@

pkg/deb/debian/control.eq3-6: pkg/deb/debian/control.eq3-6.in Makefile
	sed \
	    -e 's|@@VERSION@@|$(VERSION)|g' \
	    -e 's|@@DEB_ARCH@@|$(DEB_ARCH)|g' \
	    $< > $@

pkg/deb/debian/control.eq3-6-doc: pkg/deb/debian/control.eq3-6-doc.in Makefile
	sed \
	    -e 's|@@VERSION@@|$(VERSION)|g' \
	    $< > $@

pkg/deb/debian/control.dew: pkg/deb/debian/control.dew.in Makefile
	sed \
	    -e 's|@@DEW_VERSION@@|$(DEW_VERSION)|g' \
	    -e 's|@@DEB_ARCH@@|$(DEB_ARCH)|g' \
	    $< > $@

generate: pkg/rpm/eq3_6.spec pkg/rpm/eq3_6_dew.spec pkg/brew/eq3_6.rb pkg/brew/eq3_6_dew.rb \
          pkg/deb/debian/control.eq3-6 pkg/deb/debian/control.eq3-6-doc pkg/deb/debian/control.dew

# Regenerate sources.mk from the extracted source tree.
# Run after updating the upstream submodule, then review 'git diff sources.mk' and commit.
regen-sources: $(EXTRACT_STAMP)
	@echo "==> Regenerating sources.mk ..."
	@python3 tools/gen_sources.py > sources.mk
	@echo "==> Done. Review 'git diff sources.mk' before committing."

# Validate that sources.mk matches the extracted source tree.
# Fails with a diff if any directory has added or removed .f files.
check-sources: $(EXTRACT_STAMP)
	@python3 tools/gen_sources.py > /tmp/sources.mk.check
	@if diff -u sources.mk /tmp/sources.mk.check > /dev/null 2>&1; then \
	    echo "==> sources.mk is up to date."; \
	else \
	    echo "ERROR: sources.mk is out of sync with extracted tree. Run 'make regen-sources'."; \
	    diff -u sources.mk /tmp/sources.mk.check; \
	    exit 1; \
	fi

# ============================================================
# TESTLIB: upstream test library cases
# ============================================================
# Inputs are extracted on demand from the upstream PC test library ZIP (gitignored).
# Reference outputs are generated by make regen-testlib-refs and committed.
#
# Usage:
#   make extract-testlib   -- extract inputs + build cached data1 files
#   make regen-testlib-refs -- regenerate reference outputs and .bats files (then commit)
#   make test-testlib       -- run testlib BATS suite

# data1.com is compiled from data0.cmp (the "comprehensive" database; upstream names it cmp).
$(DATA1_CACHE)/data1.com: $(UPSTREAM_ZIP) $(BIN_DIR)/eqpt $(SRC_BASE)/eqpt/src/slist
	mkdir -p $(DATA1_CACHE)
	TMPDIR=$$(mktemp -d); \
	unzip -p $(UPSTREAM_ZIP) $(INNER_DB_TAR) \
	    | tar -xOf - db/data0.cmp.gz | gunzip > "$$TMPDIR/data0"; \
	cp $(SRC_BASE)/eqpt/src/slist "$$TMPDIR/slist"; \
	(cd "$$TMPDIR" && $(CURDIR)/$(BIN_DIR)/eqpt > run.log 2>&1) || { cat "$$TMPDIR/run.log"; rm -rf "$$TMPDIR"; exit 1; }; \
	cp "$$TMPDIR/data1" $@; \
	rm -rf "$$TMPDIR"

# Pattern rule for all other datasets where the cache name matches the archive name.
# Handles: data1.fmt, data1.hmw, data1.ymp, data1.ypf (and any future dataset added to archdb.tar).
$(DATA1_CACHE)/data1.%: $(UPSTREAM_ZIP) $(BIN_DIR)/eqpt $(SRC_BASE)/eqpt/src/slist
	mkdir -p $(DATA1_CACHE)
	TMPDIR=$$(mktemp -d); \
	unzip -p $(UPSTREAM_ZIP) $(INNER_DB_TAR) \
	    | tar -xOf - db/data0.$*.gz | gunzip > "$$TMPDIR/data0"; \
	cp $(SRC_BASE)/eqpt/src/slist "$$TMPDIR/slist"; \
	(cd "$$TMPDIR" && $(CURDIR)/$(BIN_DIR)/eqpt > run.log 2>&1) || { cat "$$TMPDIR/run.log"; rm -rf "$$TMPDIR"; exit 1; }; \
	cp "$$TMPDIR/data1" $@; \
	rm -rf "$$TMPDIR"

TESTLIB_CMP_STAMP = $(DATA1_CACHE)/.inputs-extracted-cmp
TESTLIB_FMT_STAMP = $(DATA1_CACHE)/.inputs-extracted-fmt
TESTLIB_HMW_STAMP = $(DATA1_CACHE)/.inputs-extracted-hmw
TESTLIB_YMP_STAMP = $(DATA1_CACHE)/.inputs-extracted-ymp
TESTLIB_YPF_STAMP = $(DATA1_CACHE)/.inputs-extracted-ypf
TESTLIB_XCH_STAMP = $(DATA1_CACHE)/.inputs-extracted-xch

$(TESTLIB_CMP_STAMP): $(TESTLIB_PC_ZIP) $(DATA1_CACHE)/data1.com
	mkdir -p $(TESTLIB_INPUTS)/3tlib_cmp $(TESTLIB_INPUTS)/6tlib_cmp
	cd $(TESTLIB_INPUTS) && unzip -q -o $(CURDIR)/$(TESTLIB_PC_ZIP) \
	    "3tlib_cmp/*.3i" "6tlib_cmp/*.6i"
	@touch $@

$(TESTLIB_FMT_STAMP): $(TESTLIB_PC_ZIP) $(DATA1_CACHE)/data1.fmt
	mkdir -p $(TESTLIB_INPUTS)/3tlib_fmt $(TESTLIB_INPUTS)/6tlib_fmt
	cd $(TESTLIB_INPUTS) && unzip -q -o $(CURDIR)/$(TESTLIB_PC_ZIP) \
	    "3tlib_fmt/*.3i" "6tlib_fmt/*.6i"
	@touch $@

$(TESTLIB_HMW_STAMP): $(TESTLIB_PC_ZIP) $(DATA1_CACHE)/data1.hmw
	mkdir -p $(TESTLIB_INPUTS)/3tlib_hmw $(TESTLIB_INPUTS)/6tlib_hmw
	cd $(TESTLIB_INPUTS) && unzip -q -o $(CURDIR)/$(TESTLIB_PC_ZIP) \
	    "3tlib_hmw/*.3i" "6tlib_hmw/*.6i"
	@touch $@

$(TESTLIB_YMP_STAMP): $(TESTLIB_PC_ZIP) $(DATA1_CACHE)/data1.ymp
	mkdir -p $(TESTLIB_INPUTS)/3tlib_ymp $(TESTLIB_INPUTS)/6tlib_ymp
	cd $(TESTLIB_INPUTS) && unzip -q -o $(CURDIR)/$(TESTLIB_PC_ZIP) \
	    "3tlib_ymp/*.3i" "6tlib_ymp/*.6i"
	@touch $@

$(TESTLIB_YPF_STAMP): $(TESTLIB_PC_ZIP) $(DATA1_CACHE)/data1.ypf
	mkdir -p $(TESTLIB_INPUTS)/3tlib_ypf $(TESTLIB_INPUTS)/6tlib_ypf
	cd $(TESTLIB_INPUTS) && unzip -q -o $(CURDIR)/$(TESTLIB_PC_ZIP) \
	    "3tlib_ypf/*.3i" "6tlib_ypf/*.6i"
	@touch $@

$(TESTLIB_XCH_STAMP): $(TESTLIB_PC_ZIP) $(DATA1_CACHE)/data1.com
	mkdir -p $(TESTLIB_INPUTS)/xchtlib
	cd $(TESTLIB_INPUTS) && unzip -q -o $(CURDIR)/$(TESTLIB_PC_ZIP) \
	    "xchtlib/*.3i" "xchtlib/*.6i"
	@touch $@

TESTLIB_ALL_STAMPS = $(TESTLIB_CMP_STAMP) $(TESTLIB_FMT_STAMP) $(TESTLIB_HMW_STAMP) \
                     $(TESTLIB_YMP_STAMP) $(TESTLIB_YPF_STAMP) $(TESTLIB_XCH_STAMP)

extract-testlib: $(EXTRACT_STAMP) $(TESTLIB_ALL_STAMPS)

regen-testlib-refs: $(TESTLIB_ALL_STAMPS)
	@bash tools/regen_testlib_refs.sh

test-testlib: build $(TESTLIB_ALL_STAMPS)
	@bats --recursive tests/cases/testlib/

# ============================================================
# DEW WORKSHOP: test cases from the DEW community workshop materials
# ============================================================
# Input files are committed to tests/dew/inputs/ (extracted from DEW/*.zip).
# Reference outputs are generated by make regen-dew-refs and committed.
# Three DATA0 databases compile to three sub-caches under tests/.dew_data_cache/.
#
# Usage:
#   make extract-dew-workshop   -- build data1/data2/data3 caches for all three datasets
#   make regen-dew-refs         -- regenerate reference outputs (then commit)
#   make test-dew-workshop      -- run DEW workshop BATS suite (also run by make test-dew)

DEW_DATA_CACHE   = tests/.dew_data_cache
DEW_PSAT_ZIP     = DEW/psat_data0___examples_from_enki.zip
DEW_10KBAR_ZIP   = DEW/10_kbar_300-650c.zip
DEW_DATA0_UPSTREAM = upstream-dew/EQPT/DATA0

# Compile psat DATA0 (extracted from ZIP) using bin-dew/eqpt.
$(DEW_DATA_CACHE)/psat/data1: $(DEW_PSAT_ZIP) $(DEW_BIN_DIR)/eqpt
	mkdir -p $(DEW_DATA_CACHE)/psat
	TMPD=$$(mktemp -d); \
	unzip -p $(CURDIR)/$(DEW_PSAT_ZIP) \
	    "Psat data0 & examples from ENKI/EQPTrun/DATA0" > "$$TMPD/data0"; \
	(cd "$$TMPD" && printf "n\nn\nn\n" | $(CURDIR)/$(DEW_BIN_DIR)/eqpt > run.log 2>&1) \
	    || { cat "$$TMPD/run.log"; rm -rf "$$TMPD"; exit 1; }; \
	cp "$$TMPD/data1" $(DEW_DATA_CACHE)/psat/data1; \
	cp "$$TMPD/data2" $(DEW_DATA_CACHE)/psat/data2; \
	cp "$$TMPD/data3" $(DEW_DATA_CACHE)/psat/data3; \
	rm -rf "$$TMPD"

# Compile 10kbar DATA0 (extracted from ZIP) using bin-dew/eqpt.
$(DEW_DATA_CACHE)/10kbar/data1: $(DEW_10KBAR_ZIP) $(DEW_BIN_DIR)/eqpt
	mkdir -p $(DEW_DATA_CACHE)/10kbar
	TMPD=$$(mktemp -d); \
	unzip -p $(CURDIR)/$(DEW_10KBAR_ZIP) \
	    "10 kbar 300-650C/EQPT/DATA0" > "$$TMPD/data0"; \
	(cd "$$TMPD" && printf "n\nn\nn\n" | $(CURDIR)/$(DEW_BIN_DIR)/eqpt > run.log 2>&1) \
	    || { cat "$$TMPD/run.log"; rm -rf "$$TMPD"; exit 1; }; \
	cp "$$TMPD/data1" $(DEW_DATA_CACHE)/10kbar/data1; \
	cp "$$TMPD/data2" $(DEW_DATA_CACHE)/10kbar/data2; \
	cp "$$TMPD/data3" $(DEW_DATA_CACHE)/10kbar/data3; \
	rm -rf "$$TMPD"

# Compile upstream-dew DATA0 using bin-dew/eqpt.
$(DEW_DATA_CACHE)/upstream/data1: $(DEW_DATA0_UPSTREAM) $(DEW_BIN_DIR)/eqpt
	mkdir -p $(DEW_DATA_CACHE)/upstream
	TMPD=$$(mktemp -d); \
	cp $(DEW_DATA0_UPSTREAM) "$$TMPD/data0"; \
	(cd "$$TMPD" && printf "n\nn\nn\n" | $(CURDIR)/$(DEW_BIN_DIR)/eqpt > run.log 2>&1) \
	    || { cat "$$TMPD/run.log"; rm -rf "$$TMPD"; exit 1; }; \
	cp "$$TMPD/data1" $(DEW_DATA_CACHE)/upstream/data1; \
	cp "$$TMPD/data2" $(DEW_DATA_CACHE)/upstream/data2; \
	cp "$$TMPD/data3" $(DEW_DATA_CACHE)/upstream/data3; \
	rm -rf "$$TMPD"

DEW_WORKSHOP_STAMPS = $(DEW_DATA_CACHE)/psat/data1 \
                      $(DEW_DATA_CACHE)/10kbar/data1 \
                      $(DEW_DATA_CACHE)/upstream/data1

extract-dew-workshop: $(DEW_WORKSHOP_STAMPS)

regen-dew-refs: $(DEW_WORKSHOP_STAMPS)
	@bash tools/regen_dew_refs.sh

test-dew-workshop: $(DEW_WORKSHOP_STAMPS)
	@bats tests/cases/dew/workshop/

# Compare DEW workshop outputs against the pyDEW container (simonwmatthews/pydew:v2.15).
# Requires: podman or docker, DEW/*.zip files.
# --regen writes committed reference outputs to tests/dew/expected/container/.
compare-dew-container:
	@bash tools/compare_dew_container.sh

regen-container-refs:
	@bash tools/compare_dew_container.sh --regen

# ============================================================
# PACKAGING
# All package artifacts are written to pkg/dist/.
# ============================================================

# Per-platform packaging targets for the farm build.
PLATFORM_PKGS_fedora := rpm rpm-dew
PLATFORM_PKGS_ubuntu := deb deb-dew
PLATFORM_PKGS_mac    := brew brew-dew

# Pull the latest commit from origin.  Runs on whichever machine make is
# invoked on, so it reads that machine's ssh_build_farm.mk for REPO_URL.
sync:
	git pull --ff-only $(REPO_URL) main

# Entry point invoked on each farm builder (locally or via SSH).
# sync pulls the latest commit; submodules, build, test, and package follow.
# PLATFORM_TARGET must be set to 'fedora', 'ubuntu', or 'mac'.
platform-build: sync
	$(MAKE) fetch fetch-dew
	$(MAKE) generate build build-dew test test-dew
	$(MAKE) $(PLATFORM_PKGS_$(PLATFORM_TARGET))

# -- RPM -------------------------------------------------------
rpm: pkg/rpm/eq3_6.spec docs
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: RPM packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which rpmbuild > /dev/null 2>&1 || \
	    { echo "ERROR: rpmbuild not found. Install rpm-build."; exit 1; }
	@mkdir -p pkg/rpm/build/BUILD pkg/rpm/build/RPMS \
	           pkg/rpm/build/SOURCES pkg/rpm/build/SPECS pkg/rpm/build/SRPMS
	cp $(UPSTREAM_ZIP) pkg/rpm/build/SOURCES/EQ36_80a_Linux.zip
	cp $(DOC_138894) pkg/rpm/build/SOURCES/138894.pdf
	cp $(DOC_138639) pkg/rpm/build/SOURCES/138639.pdf
	cp $(DOC_138643) pkg/rpm/build/SOURCES/138643.pdf
	cp $(DOC_138820) pkg/rpm/build/SOURCES/138820.pdf
	rpmbuild --define "_topdir $(CURDIR)/pkg/rpm/build" \
	         -bb pkg/rpm/eq3_6.spec
	@mkdir -p pkg/dist
	find pkg/rpm/build/RPMS -name '*.rpm' -exec cp {} pkg/dist/ \;
	@echo "RPM written to pkg/dist/"

# -- DEB -------------------------------------------------------
deb: build pkg/deb/debian/control.eq3-6
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: .deb packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which dpkg-deb > /dev/null 2>&1 || \
	    { echo "ERROR: dpkg-deb not found. Install dpkg-dev."; exit 1; }
	@# Binary package
	@mkdir -p pkg/deb/staging/usr/bin pkg/deb/staging/DEBIAN pkg/dist
	cp $(BIN_DIR)/eq3nr $(BIN_DIR)/eq6 $(BIN_DIR)/eqpt \
	   $(BIN_DIR)/xcon3 $(BIN_DIR)/xcon6 pkg/deb/staging/usr/bin/
	cp pkg/deb/debian/control.eq3-6 pkg/deb/staging/DEBIAN/control
	dpkg-deb --build pkg/deb/staging pkg/dist/eq3-6_$(VERSION)_$(DEB_ARCH).deb
	@echo ".deb written to pkg/dist/"

deb-doc: docs pkg/deb/debian/control.eq3-6-doc
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: .deb packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which dpkg-deb > /dev/null 2>&1 || \
	    { echo "ERROR: dpkg-deb not found. Install dpkg-dev."; exit 1; }
	@# Documentation package
	@mkdir -p pkg/deb/staging-doc/usr/share/doc/eq3-6 \
	           pkg/deb/staging-doc/DEBIAN pkg/dist
	cp $(DOCS) pkg/deb/staging-doc/usr/share/doc/eq3-6/
	cp pkg/deb/debian/control.eq3-6-doc pkg/deb/staging-doc/DEBIAN/control
	dpkg-deb --build pkg/deb/staging-doc pkg/dist/eq3-6-doc_$(VERSION)_all.deb
	@echo "Docs .deb written to pkg/dist/"

# -- Homebrew --------------------------------------------------
# Homebrew 4+ requires formulae to live in a tap; local .rb files are no longer
# accepted by `brew install`. This target stages the formula into a local tap
# (local/eq3-6) and installs from there.
brew: pkg/brew/eq3_6.rb
	@which brew > /dev/null 2>&1 || \
	    { echo "ERROR: brew not found. See https://brew.sh"; exit 1; }
	@set -e; \
	 TAP_DIR="$$(brew --repository)/Library/Taps/local/homebrew-eq3-6"; \
	 mkdir -p "$$TAP_DIR/Formula"; \
	 if [ ! -d "$$TAP_DIR/.git" ]; then \
	     git -C "$$TAP_DIR" init -q; \
	     git -C "$$TAP_DIR" commit --allow-empty -qm "init"; \
	 fi; \
	 cp pkg/brew/eq3_6.rb "$$TAP_DIR/Formula/eq3_6.rb"; \
	 git -C "$$TAP_DIR" add "Formula/eq3_6.rb"; \
	 git -C "$$TAP_DIR" diff --cached --quiet || git -C "$$TAP_DIR" commit -qm "update"; \
	 brew install --build-from-source local/eq3-6/eq3_6
	@echo "Done. Run 'brew test eq3_6' to verify."

# -- DEW RPM ---------------------------------------------------
# Builds from source in rpmbuild's isolated sandbox; no pre-built
# bin-dew/ binaries are required on the host.
rpm-dew: pkg/rpm/eq3_6_dew.spec
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: RPM packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which rpmbuild > /dev/null 2>&1 || \
	    { echo "ERROR: rpmbuild not found. Install rpm-build."; exit 1; }
	@mkdir -p pkg/rpm/build/BUILD pkg/rpm/build/RPMS \
	           pkg/rpm/build/SOURCES pkg/rpm/build/SPECS pkg/rpm/build/SRPMS
	git -C $(DEW_UPSTREAM) archive --prefix=SUPCRTandEQs/ HEAD \
	    | gzip > pkg/rpm/build/SOURCES/SUPCRTandEQs_DEW_activities.tar.gz
	cp patches/dew-*.patch pkg/rpm/build/SOURCES/
	rpmbuild --define "_topdir $(CURDIR)/pkg/rpm/build" \
	         -bb pkg/rpm/eq3_6_dew.spec
	@mkdir -p pkg/dist
	find pkg/rpm/build/RPMS -name 'eq3-6-dew*.rpm' -exec cp {} pkg/dist/ \;
	@echo "DEW RPM written to pkg/dist/"

# -- DEW deb ---------------------------------------------------
# Copies pre-built bin-dew/ binaries into a staging tree and calls dpkg-deb.
deb-dew: build-dew pkg/deb/debian/control.dew
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: .deb packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which dpkg-deb > /dev/null 2>&1 || \
	    { echo "ERROR: dpkg-deb not found. Install dpkg-dev."; exit 1; }
	@mkdir -p pkg/deb/staging-dew/usr/bin \
	           pkg/deb/staging-dew/usr/share/eq3-6-dew \
	           pkg/deb/staging-dew/DEBIAN \
	           pkg/dist
	cp $(DEW_BIN_DIR)/eqpt     pkg/deb/staging-dew/usr/bin/dew-eqpt
	cp $(DEW_BIN_DIR)/eq3      pkg/deb/staging-dew/usr/bin/dew-eq3
	cp $(DEW_BIN_DIR)/eq6      pkg/deb/staging-dew/usr/bin/dew-eq6
	cp $(DEW_BIN_DIR)/supcrt   pkg/deb/staging-dew/usr/bin/dew-supcrt
	cp $(DEW_BIN_DIR)/cprons92 pkg/deb/staging-dew/usr/bin/dew-cprons92
	chmod 755 pkg/deb/staging-dew/usr/bin/dew-*
	cp $(DEW_UPSTREAM)/EQPT/DATA0       pkg/deb/staging-dew/usr/share/eq3-6-dew/DATA0
	cp $(DEW_UPSTREAM)/CPRONS/sprons93  pkg/deb/staging-dew/usr/share/eq3-6-dew/sprons93
	cp pkg/deb/debian/control.dew pkg/deb/staging-dew/DEBIAN/control
	dpkg-deb --build pkg/deb/staging-dew pkg/dist/eq3-6-dew_$(DEW_VERSION)_$(DEB_ARCH).deb
	@echo "DEW .deb written to pkg/dist/"

# -- DEW Homebrew ----------------------------------------------
brew-dew: pkg/brew/eq3_6_dew.rb
	@which brew > /dev/null 2>&1 || \
	    { echo "ERROR: brew not found. See https://brew.sh"; exit 1; }
	@set -e; \
	 TAP_DIR="$$(brew --repository)/Library/Taps/local/homebrew-eq3-6"; \
	 mkdir -p "$$TAP_DIR/Formula"; \
	 if [ ! -d "$$TAP_DIR/.git" ]; then \
	     git -C "$$TAP_DIR" init -q; \
	     git -C "$$TAP_DIR" commit --allow-empty -qm "init"; \
	 fi; \
	 cp pkg/brew/eq3_6_dew.rb "$$TAP_DIR/Formula/eq3_6_dew.rb"; \
	 git -C "$$TAP_DIR" add "Formula/eq3_6_dew.rb"; \
	 git -C "$$TAP_DIR" diff --cached --quiet || git -C "$$TAP_DIR" commit -qm "update"; \
	 brew install --build-from-source local/eq3-6/eq3_6_dew
	@echo "Done. Run 'brew test eq3_6_dew' to verify."

# -- Documentation package (tar of PDFs) -----------------------
# Downloads docs first if not already present.
docs-package: docs
	@mkdir -p pkg/dist
	tar -czf pkg/dist/eq3-6-docs_8.0a.tar.gz \
	    -C $(DOCS_DIR) \
	    --transform 's|^|eq3-6-docs_8.0a/|' \
	    138894.pdf 138639.pdf 138643.pdf 138820.pdf SHA256SUMS
	@echo "Docs package written to pkg/dist/eq3-6-docs_8.0a.tar.gz"

# ============================================================
# FARM BUILD: parallel packaging across all three platforms
# ============================================================
# Requires ssh_build_farm.mk (copy from ssh_build_farm.mk.example).
# Pushes current commit, then builds all three platforms in parallel.
# *_CONNECTION is empty for the local builder, 'ssh <host>' for remote.
#
# Usage:  make farm

farm: _farm-check-config farm-push
	@$(MAKE) --no-print-directory -j3 --output-sync=target \
	    farm-fedora farm-ubuntu farm-mac
	@$(MAKE) --no-print-directory farm-collect

_farm-check-config:
ifeq (,$(wildcard ssh_build_farm.mk))
	$(error ssh_build_farm.mk not found. Copy ssh_build_farm.mk.example and fill in builder hostnames.)
endif

farm-push:
	git push

farm-fedora:
	$(FEDORA_CONNECTION) $(MAKE) -C $(FEDORA_FARM_REPO) platform-build PLATFORM_TARGET=fedora

farm-ubuntu:
	$(UBUNTU_CONNECTION) $(MAKE) -C $(UBUNTU_FARM_REPO) platform-build PLATFORM_TARGET=ubuntu

farm-mac:
	$(MAC_CONNECTION) $(MAKE) -C $(MAC_FARM_REPO) platform-build PLATFORM_TARGET=mac

# Collect packages from all remote builders into local pkg/dist/.
# Remote builders are those where *_CONNECTION is non-empty (i.e. not this machine).
# Mac is omitted: 'make brew' installs locally and produces no pkg/dist/ artifacts.
farm-collect: _farm-check-config
	mkdir -p pkg/dist
ifneq ($(FEDORA_CONNECTION),)
	$(FEDORA_CONNECTION) tar -C $(FEDORA_FARM_REPO)/pkg/dist -cf - . | tar -C pkg/dist -xf -
endif
ifneq ($(UBUNTU_CONNECTION),)
	$(UBUNTU_CONNECTION) tar -C $(UBUNTU_FARM_REPO)/pkg/dist -cf - . | tar -C pkg/dist -xf -
endif

# ============================================================
# CLEAN
# ============================================================
test: build check-sources pkg/rpm/eq3_6.spec pkg/brew/eq3_6.rb
	@bats --recursive tests/cases/smoke tests/cases/eq3nr tests/cases/eq6 tests/cases/packaging

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)

# distclean also removes extracted source, downloaded docs, and packaging build trees.
# Does NOT remove upstream/ (submodule), pkg/ source files, or .gitmodules.
# $(DOCS) removes only the gitignored PDF files; docs/SHA256SUMS is tracked and must stay.
distclean: clean clean-dew
	rm -rf $(SRC_BASE) \
	    $(DOCS) \
	    pkg/rpm/build pkg/rpm/eq3_6.spec pkg/rpm/eq3_6_dew.spec \
	    pkg/deb/staging pkg/deb/staging-doc pkg/deb/staging-dew \
	    pkg/deb/debian/control.eq3-6 pkg/deb/debian/control.eq3-6-doc pkg/deb/debian/control.dew \
	    pkg/brew/eq3_6.rb pkg/brew/eq3_6_dew.rb $(DEW_SRC_TARBALL) \
	    pkg/dist \
	    $(DATA1_CACHE) $(TESTLIB_INPUTS) \
	    $(DEW_DATA_CACHE)

.PHONY: all build fetch extract docs docs-package generate symlinks symlinks-dew \
        rpm deb deb-doc brew test clean distclean \
        fetch-dew patch-dew build-dew test-dew clean-dew \
        rpm-dew deb-dew brew-dew \
        farm _farm-check-config farm-push farm-fedora farm-ubuntu farm-mac farm-collect platform-build sync \
        extract-testlib regen-testlib-refs test-testlib \
        extract-dew-workshop regen-dew-refs test-dew-workshop \
        compare-dew-container regen-container-refs
