# ============================================================
# EQ36 build system
# Builds EQ3/6 v8.0a Fortran executables from the upstream ZIP
# stored in the git submodule at upstream/.
#
# Quick start:
#   make fetch    - initialize upstream submodule
#   make          - extract + build all executables
#   make docs     - download documentation PDFs to docs/
#
# Packaging:
#   make rpm      - build RPM (Linux, requires rpm-build)
#   make deb      - build .deb (Linux, requires dpkg-dev debhelper)
#   make brew     - install via Homebrew formula
#
# Manual symlink install (LINK_DIR must be set explicitly):
#   make symlinks LINK_DIR=/usr/local/bin
# ============================================================

FC     = gfortran
# -std=legacy accepts old-style Fortran 77 FORMAT strings (missing commas
# between descriptors) that gfortran 15+ rejects at runtime by default.
FFLAGS = -O2 -std=legacy

# Upstream ZIP (provided by the git submodule)
UPSTREAM_ZIP  = upstream/EQ36_80a_Linux.zip
INNER_SRC_TAR = Linux/EQ3_6v8.0a/archsrc.tar

# Source extraction root (gitignored, regenerated by make extract)
SRC_BASE = src

# Build output directories
BIN_DIR = bin
OBJ_DIR = obj

# Stamp file so extraction only runs once (or when the ZIP changes)
EXTRACT_STAMP = $(SRC_BASE)/.extracted

# Documentation PDFs from OSTI (downloaded by make docs; gitignored)
DOCS_DIR       = docs
OSTI_BASE      = https://www.osti.gov/servlets/purl
DOC_138894     = $(DOCS_DIR)/138894.pdf   # Part 1: EQ3/6 overview and installation guide
DOC_138639     = $(DOCS_DIR)/138639.pdf   # Part 2: EQPT user's guide
DOC_138643     = $(DOCS_DIR)/138643.pdf   # Part 3: EQ3NR theoretical manual and user's guide
DOC_138820     = $(DOCS_DIR)/138820.pdf   # Part 4: EQ6 theoretical manual and user's guide
DOCS           = $(DOC_138894) $(DOC_138639) $(DOC_138643) $(DOC_138820)
DOCS_SHA256    = docs/SHA256SUMS

# Platform detection (used for packaging target warnings)
UNAME_S := $(shell uname -s)

# SHA256 verification command (sha256sum on Linux, shasum on macOS)
ifeq ($(UNAME_S),Darwin)
  SHA256_CHECK = shasum -a 256 -c
else
  SHA256_CHECK = sha256sum -c
endif

# ---- Source directories ----------------------------------------
EQLIBU_SRC_DIR = $(SRC_BASE)/eqlibu/src
EQLIBG_SRC_DIR = $(SRC_BASE)/eqlibg/src
EQLIB_SRC_DIR  = $(SRC_BASE)/eqlib/src
EQ3NR_SRC_DIR  = $(SRC_BASE)/eq3nr/src
EQ6_SRC_DIR    = $(SRC_BASE)/eq6/src
EQPT_SRC_DIR   = $(SRC_BASE)/eqpt/src
XCON3_SRC_DIR  = $(SRC_BASE)/xcon3/src
XCON6_SRC_DIR  = $(SRC_BASE)/xcon6/src

# ---- Executables -----------------------------------------------
TARGETS = \
    $(BIN_DIR)/eq3nr \
    $(BIN_DIR)/eq6 \
    $(BIN_DIR)/eqpt \
    $(BIN_DIR)/xcon3 \
    $(BIN_DIR)/xcon6

# ---- Source file lists -----------------------------------------
# Note: wildcards expand only after extraction; see EXTRACT_STAMP dependency.
EQLIBU_SRC = $(wildcard $(EQLIBU_SRC_DIR)/*.f)
EQLIBG_SRC = $(wildcard $(EQLIBG_SRC_DIR)/*.f)
EQLIB_SRC  = $(wildcard $(EQLIB_SRC_DIR)/*.f)
EQ3NR_SRC  = $(wildcard $(EQ3NR_SRC_DIR)/*.f)
EQPT_SRC   = $(wildcard $(EQPT_SRC_DIR)/*.f)
XCON3_SRC  = $(wildcard $(XCON3_SRC_DIR)/*.f)
XCON6_SRC  = $(wildcard $(XCON6_SRC_DIR)/*.f)

# EQ6: modules must compile before the rest (they define Fortran modules
# consumed via USE statements in several other eq6 source files).
EQ6_MODULE_SRC = $(EQ6_SRC_DIR)/mod6pt.f $(EQ6_SRC_DIR)/mod6xf.f
EQ6_OTHER_SRC  = $(filter-out $(EQ6_MODULE_SRC), $(wildcard $(EQ6_SRC_DIR)/*.f))

# ---- Object file lists -----------------------------------------
EQLIBU_OBJ     = $(patsubst $(EQLIBU_SRC_DIR)/%.f, $(OBJ_DIR)/%.o, $(EQLIBU_SRC))
EQLIBG_OBJ     = $(patsubst $(EQLIBG_SRC_DIR)/%.f, $(OBJ_DIR)/%.o, $(EQLIBG_SRC))
EQLIB_OBJ      = $(patsubst $(EQLIB_SRC_DIR)/%.f,  $(OBJ_DIR)/%.o, $(EQLIB_SRC))
EQ3NR_OBJ      = $(patsubst $(EQ3NR_SRC_DIR)/%.f,  $(OBJ_DIR)/%.o, $(EQ3NR_SRC))
EQ6_MODULE_OBJ = $(OBJ_DIR)/mod6pt.o $(OBJ_DIR)/mod6xf.o
EQ6_OTHER_OBJ  = $(patsubst $(EQ6_SRC_DIR)/%.f,    $(OBJ_DIR)/%.o, $(EQ6_OTHER_SRC))
EQ6_OBJ        = $(EQ6_MODULE_OBJ) $(EQ6_OTHER_OBJ)
EQPT_OBJ       = $(patsubst $(EQPT_SRC_DIR)/%.f,   $(OBJ_DIR)/%.o, $(EQPT_SRC))
XCON3_OBJ      = $(patsubst $(XCON3_SRC_DIR)/%.f,  $(OBJ_DIR)/%.o, $(XCON3_SRC))
XCON6_OBJ      = $(patsubst $(XCON6_SRC_DIR)/%.f,  $(OBJ_DIR)/%.o, $(XCON6_SRC))

# ============================================================
# DEFAULT TARGET
# ============================================================
.DEFAULT_GOAL := all

all: build

build: $(EXTRACT_STAMP) $(TARGETS)

# ============================================================
# FETCH: initialize / update the upstream git submodule
# ============================================================
fetch:
	git submodule update --init upstream

# ============================================================
# EXTRACT: unpack source from upstream ZIP, then decompress
#
# archsrc.tar stores every .f and .h (and .k) file as .f.gz /
# .h.gz / .k.gz.  gfortran cannot compile compressed files, so
# gunzip is mandatory before compilation.
#
# Uses 'xargs gunzip' rather than 'gunzip -r' for macOS compat
# (BSD gunzip on macOS does not support the -r flag).
# ============================================================
$(EXTRACT_STAMP): $(UPSTREAM_ZIP)
	@test -f $(UPSTREAM_ZIP) || \
	    { echo "ERROR: $(UPSTREAM_ZIP) not found. Run: make fetch"; exit 1; }
	@echo "==> Extracting Fortran sources from $(UPSTREAM_ZIP) ..."
	@mkdir -p $(SRC_BASE)
	unzip -p $(UPSTREAM_ZIP) $(INNER_SRC_TAR) | tar -xf - -C $(SRC_BASE)/
	@echo "==> Decompressing .gz source files ..."
	find $(SRC_BASE) -name '*.gz' | xargs gunzip
	@touch $@
	@echo "==> Extraction complete."

extract: $(EXTRACT_STAMP)

# ============================================================
# DOCS: download documentation PDFs from OSTI
# ============================================================
# Individual PDF rules — each verifies its SHA256 after download.
# If verification fails, the partial file is removed and make aborts.
$(DOC_138894):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138894
	cd $(DOCS_DIR) && grep 138894.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

$(DOC_138639):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138639
	cd $(DOCS_DIR) && grep 138639.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

$(DOC_138643):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138643
	cd $(DOCS_DIR) && grep 138643.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

$(DOC_138820):
	@mkdir -p $(DOCS_DIR)
	curl -L -o $@ $(OSTI_BASE)/138820
	cd $(DOCS_DIR) && grep 138820.pdf $(CURDIR)/$(DOCS_SHA256) | $(SHA256_CHECK) --strict - || { rm -f $@; exit 1; }

docs: $(DOCS)

# ============================================================
# COMPILATION: pattern rules
#
# -J$(OBJ_DIR) tells gfortran to write .mod files to obj/ and
# to search obj/ when resolving USE statements.
#
# Include paths (e.g. '../../eqlib/inc/eqldef.h') are relative
# to the source file's location — gfortran resolves them from
# the source directory, so no -I flags are needed.
#
# All 496 source basenames are globally unique across the 8
# component directories, so a single flat obj/ is safe.
# ============================================================
$(OBJ_DIR)/%.o: $(EQLIBU_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQLIBG_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQLIB_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQ3NR_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

# EQ6 module files — explicit targets, no extra prerequisites
$(OBJ_DIR)/mod6pt.o: $(EQ6_SRC_DIR)/mod6pt.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/mod6xf.o: $(EQ6_SRC_DIR)/mod6xf.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

# Non-module EQ6 files: order-only dep ensures modules are compiled first
$(EQ6_OTHER_OBJ): | $(EQ6_MODULE_OBJ)

$(OBJ_DIR)/%.o: $(EQ6_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(EQPT_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(XCON3_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

$(OBJ_DIR)/%.o: $(XCON6_SRC_DIR)/%.f $(EXTRACT_STAMP)
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	$(FC) $(FFLAGS) -c $< -o $@ -J$(OBJ_DIR)

# ============================================================
# LINK: build executables
# ============================================================
$(BIN_DIR)/eq3nr: $(EQLIBU_OBJ) $(EQLIBG_OBJ) $(EQLIB_OBJ) $(EQ3NR_OBJ)
	$(FC) $(FFLAGS) -o $@ $^

$(BIN_DIR)/eq6: $(EQLIBU_OBJ) $(EQLIBG_OBJ) $(EQLIB_OBJ) $(EQ6_OBJ)
	$(FC) $(FFLAGS) -o $@ $^

$(BIN_DIR)/eqpt: $(EQLIBU_OBJ) $(EQPT_OBJ)
	$(FC) $(FFLAGS) -o $@ $^

$(BIN_DIR)/xcon3: $(EQLIBU_OBJ) $(XCON3_OBJ)
	$(FC) $(FFLAGS) -o $@ $^

$(BIN_DIR)/xcon6: $(EQLIBU_OBJ) $(XCON6_OBJ)
	$(FC) $(FFLAGS) -o $@ $^

# ============================================================
# SYMLINKS: create symlinks in a user-specified directory.
# LINK_DIR has no default — it must be passed on the command line.
# Example: make symlinks LINK_DIR=~/.local/bin
# ============================================================
symlinks: _check-link-dir $(TARGETS)
	mkdir -p $(LINK_DIR)
	ln -sf $(CURDIR)/$(BIN_DIR)/eq3nr  $(LINK_DIR)/eq3nr
	ln -sf $(CURDIR)/$(BIN_DIR)/eq6    $(LINK_DIR)/eq6
	ln -sf $(CURDIR)/$(BIN_DIR)/eqpt   $(LINK_DIR)/eqpt
	ln -sf $(CURDIR)/$(BIN_DIR)/xcon3  $(LINK_DIR)/xcon3
	ln -sf $(CURDIR)/$(BIN_DIR)/xcon6  $(LINK_DIR)/xcon6
	@echo "Symlinks created in $(LINK_DIR)"

.PHONY: _check-link-dir
_check-link-dir:
ifndef LINK_DIR
	$(error LINK_DIR is not set. Usage: make symlinks LINK_DIR=/path/to/bin)
endif

# ============================================================
# PACKAGING
# All package artifacts are written to pkg/dist/.
# ============================================================

# -- RPM -------------------------------------------------------
rpm: docs
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: RPM packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which rpmbuild > /dev/null 2>&1 || \
	    { echo "ERROR: rpmbuild not found. Install rpm-build."; exit 1; }
	@mkdir -p pkg/rpm/build/BUILD pkg/rpm/build/RPMS \
	           pkg/rpm/build/SOURCES pkg/rpm/build/SPECS pkg/rpm/build/SRPMS
	cp $(UPSTREAM_ZIP) pkg/rpm/build/SOURCES/EQ36_80a_Linux.zip
	cp $(DOC_138894) pkg/rpm/build/SOURCES/138894.pdf
	cp $(DOC_138639) pkg/rpm/build/SOURCES/138639.pdf
	cp $(DOC_138643) pkg/rpm/build/SOURCES/138643.pdf
	cp $(DOC_138820) pkg/rpm/build/SOURCES/138820.pdf
	rpmbuild --define "_topdir $(CURDIR)/pkg/rpm/build" \
	         -bb pkg/rpm/eq3_6.spec
	@mkdir -p pkg/dist
	find pkg/rpm/build/RPMS -name '*.rpm' -exec cp {} pkg/dist/ \;
	@echo "RPM written to pkg/dist/"

# -- DEB -------------------------------------------------------
deb: build
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: .deb packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which dpkg-deb > /dev/null 2>&1 || \
	    { echo "ERROR: dpkg-deb not found. Install dpkg-dev."; exit 1; }
	@# Binary package
	@mkdir -p pkg/deb/staging/usr/bin pkg/deb/staging/DEBIAN pkg/dist
	cp $(BIN_DIR)/eq3nr $(BIN_DIR)/eq6 $(BIN_DIR)/eqpt \
	   $(BIN_DIR)/xcon3 $(BIN_DIR)/xcon6 pkg/deb/staging/usr/bin/
	cp pkg/deb/debian/control pkg/deb/staging/DEBIAN/control
	dpkg-deb --build pkg/deb/staging pkg/dist/eq3-6_8.0a_amd64.deb
	@echo ".deb written to pkg/dist/"

deb-doc: docs
ifneq ($(UNAME_S),Linux)
	@echo "WARNING: .deb packaging is designed for Linux (you are on $(UNAME_S))"
endif
	@which dpkg-deb > /dev/null 2>&1 || \
	    { echo "ERROR: dpkg-deb not found. Install dpkg-dev."; exit 1; }
	@# Documentation package
	@mkdir -p pkg/deb/staging-doc/usr/share/doc/eq3-6 \
	           pkg/deb/staging-doc/DEBIAN pkg/dist
	cp $(DOCS) pkg/deb/staging-doc/usr/share/doc/eq3-6/
	grep -A5 'Package: eq3-6-doc' pkg/deb/debian/control \
	    | grep -v '^--' > pkg/deb/staging-doc/DEBIAN/control
	dpkg-deb --build pkg/deb/staging-doc pkg/dist/eq3-6-doc_8.0a_all.deb
	@echo "Docs .deb written to pkg/dist/"

# -- Homebrew --------------------------------------------------
brew:
	@which brew > /dev/null 2>&1 || \
	    { echo "ERROR: brew not found. See https://brew.sh"; exit 1; }
	brew install --build-from-source pkg/brew/eq3_6.rb
	@echo "Homebrew install complete."

# -- Documentation package (tar of PDFs) -----------------------
# Downloads docs first if not already present.
docs-package: docs
	@mkdir -p pkg/dist
	tar -czf pkg/dist/eq3-6-docs_8.0a.tar.gz \
	    -C $(DOCS_DIR) \
	    --transform 's|^|eq3-6-docs_8.0a/|' \
	    138894.pdf 138639.pdf 138643.pdf 138820.pdf SHA256SUMS
	@echo "Docs package written to pkg/dist/eq3-6-docs_8.0a.tar.gz"

# ============================================================
# CLEAN
# ============================================================
test: build
	@bats --recursive tests/cases/

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)

# distclean also removes extracted source, downloaded docs, and packaging build trees.
# Does NOT remove upstream/ (submodule), pkg/ source files, or .gitmodules.
distclean: clean
	rm -rf $(SRC_BASE) $(DOCS_DIR) pkg/rpm/build pkg/deb/staging pkg/deb/staging-doc pkg/dist

.PHONY: all build fetch extract docs docs-package symlinks rpm deb deb-doc brew test clean distclean
