#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" ymp; }
teardown() { teardown_workdir; }

@test "3tlib_ymp/acidmwb: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/acidmwb.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/acidmwb.out"
}

@test "3tlib_ymp/bo3bufs: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/bo3bufs.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/bo3bufs.out"
}

@test "3tlib_ymp/cahco3: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/cahco3.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/cahco3.out"
}

@test "3tlib_ymp/co3aqui: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/co3aqui.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/co3aqui.out"
}

@test "3tlib_ymp/cristoba: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/cristoba.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/cristoba.out"
}

@test "3tlib_ymp/custbuf: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/custbuf.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/custbuf.out"
}

@test "3tlib_ymp/deionw: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/deionw.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/deionw.out"
}

@test "3tlib_ymp/fo2mineq: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/fo2mineq.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/fo2mineq.out"
}

@test "3tlib_ymp/h2so4p02: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/h2so4p02.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/h2so4p02.out"
}

@test "3tlib_ymp/h2so4p1: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/h2so4p1.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/h2so4p1.out"
}

@test "3tlib_ymp/hcl1: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/hcl1.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/hcl1.out"
}

@test "3tlib_ymp/hclp02: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/hclp02.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/hclp02.out"
}

@test "3tlib_ymp/hclp1: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/hclp1.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/hclp1.out"
}

@test "3tlib_ymp/henleyph: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/henleyph.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/henleyph.out"
}

@test "3tlib_ymp/j13w: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/j13w.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/j13w.out"
}

@test "3tlib_ymp/j13wa: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/j13wa.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/j13wa.out"
}

@test "3tlib_ymp/j13wsf: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/j13wsf.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/j13wsf.out"
}

@test "3tlib_ymp/oxcalhem: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/oxcalhem.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/oxcalhem.out"
}

@test "3tlib_ymp/ph4hcl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/ph4hcl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/ph4hcl.out"
}

@test "3tlib_ymp/quenchfl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/quenchfl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/quenchfl.out"
}

@test "3tlib_ymp/rwpar: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/rwpar.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/rwpar.out"
}

@test "3tlib_ymp/rwssdiag: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/rwssdiag.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/rwssdiag.out"
}

@test "3tlib_ymp/rwtst: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/rwtst.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/rwtst.out"
}

@test "3tlib_ymp/sio2: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/sio2.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/sio2.out"
}

@test "3tlib_ymp/sw2vxch: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/sw2vxch.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/sw2vxch.out"
}

@test "3tlib_ymp/swauto: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swauto.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swauto.out"
}

@test "3tlib_ymp/swbasw: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swbasw.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swbasw.out"
}

@test "3tlib_ymp/swcaarag: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swcaarag.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swcaarag.out"
}

@test "3tlib_ymp/swco2: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swco2.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swco2.out"
}

@test "3tlib_ymp/swg1sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swg1sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swg1sx.out"
}

@test "3tlib_ymp/swgeo: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swgeo.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swgeo.out"
}

@test "3tlib_ymp/swmaj: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swmaj.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swmaj.out"
}

@test "3tlib_ymp/swmajd: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swmajd.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swmajd.out"
}

@test "3tlib_ymp/swmjdofe: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swmjdofe.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swmjdofe.out"
}

@test "3tlib_ymp/swpar: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swpar.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swpar.out"
}

@test "3tlib_ymp/swpharag: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swpharag.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swpharag.out"
}

@test "3tlib_ymp/swrdxcp: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swrdxcp.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swrdxcp.out"
}

@test "3tlib_ymp/swtst: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swtst.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swtst.out"
}

@test "3tlib_ymp/swv1sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swv1sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swv1sx.out"
}

@test "3tlib_ymp/swv1sxca: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swv1sxca.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swv1sxca.out"
}

@test "3tlib_ymp/swv2sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ymp/swv2sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ymp/swv2sx.out"
}

