#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" hmw; }
teardown() { teardown_workdir; }

@test "3tlib_hmw/calnacl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/calnacl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/calnacl.out"
}

@test "3tlib_hmw/canshbr: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/canshbr.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/canshbr.out"
}

@test "3tlib_hmw/deadsea: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/deadsea.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/deadsea.out"
}

@test "3tlib_hmw/epsomite: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/epsomite.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/epsomite.out"
}

@test "3tlib_hmw/gypsum: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/gypsum.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/gypsum.out"
}

@test "3tlib_hmw/swlmahcl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/swlmahcl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/swlmahcl.out"
}

@test "3tlib_hmw/swmajp: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/swmajp.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/swmajp.out"
}

@test "3tlib_hmw/swphcl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/swphcl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/swphcl.out"
}

@test "3tlib_hmw/swv1sxk: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_hmw/swv1sxk.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_hmw/swv1sxk.out"
}

