#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" ypf; }
teardown() { teardown_workdir; }

@test "3tlib_ypf/arcmir: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ypf/arcmir.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ypf/arcmir.out"
}

@test "3tlib_ypf/arcsyl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ypf/arcsyl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ypf/arcsyl.out"
}

@test "3tlib_ypf/hal100: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ypf/hal100.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ypf/hal100.out"
}

@test "3tlib_ypf/syl100: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ypf/syl100.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ypf/syl100.out"
}

@test "3tlib_ypf/Sylcacl2: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ypf/Sylcacl2.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ypf/Sylcacl2.out"
}

@test "3tlib_ypf/sylhal2: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ypf/sylhal2.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ypf/sylhal2.out"
}

@test "3tlib_ypf/sylhal: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_ypf/sylhal.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_ypf/sylhal.out"
}

