#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" fmt; }
teardown() { teardown_workdir; }

@test "3tlib_fmt/c4pgwbN2: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_fmt/c4pgwbN2.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_fmt/c4pgwbN2.out"
}

@test "3tlib_fmt/deadseaw: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_fmt/deadseaw.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_fmt/deadseaw.out"
}

@test "3tlib_fmt/f24vc7b3: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_fmt/f24vc7b3.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_fmt/f24vc7b3.out"
}

@test "3tlib_fmt/f24vc7k4: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_fmt/f24vc7k4.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_fmt/f24vc7k4.out"
}

@test "3tlib_fmt/f24vc7m: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_fmt/f24vc7m.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_fmt/f24vc7m.out"
}

@test "3tlib_fmt/gypnaclx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_fmt/gypnaclx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_fmt/gypnaclx.out"
}

@test "3tlib_fmt/swmajm: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_fmt/swmajm.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "3tlib_fmt/swmajm.out"
}

