#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" com; }
teardown() { teardown_workdir; }

@test "3tlib_cmp/acidmwb: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/acidmwb.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/acidmwb.out"
}

@test "3tlib_cmp/bo3bufs: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/bo3bufs.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/bo3bufs.out"
}

@test "3tlib_cmp/cahco3: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/cahco3.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/cahco3.out"
}

@test "3tlib_cmp/co3aqui: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/co3aqui.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/co3aqui.out"
}

@test "3tlib_cmp/cristoba: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/cristoba.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/cristoba.out"
}

@test "3tlib_cmp/custbuf: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/custbuf.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/custbuf.out"
}

@test "3tlib_cmp/deionw: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/deionw.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/deionw.out"
}

@test "3tlib_cmp/fo2mineq: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/fo2mineq.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/fo2mineq.out"
}

@test "3tlib_cmp/h2so4p02: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/h2so4p02.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/h2so4p02.out"
}

@test "3tlib_cmp/h2so4p1: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/h2so4p1.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/h2so4p1.out"
}

@test "3tlib_cmp/hcl1: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/hcl1.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/hcl1.out"
}

@test "3tlib_cmp/hclp02: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/hclp02.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/hclp02.out"
}

@test "3tlib_cmp/hclp1: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/hclp1.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/hclp1.out"
}

@test "3tlib_cmp/henleyph: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/henleyph.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/henleyph.out"
}

@test "3tlib_cmp/j13w: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/j13w.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/j13w.out"
}

@test "3tlib_cmp/j13wa: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/j13wa.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/j13wa.out"
}

@test "3tlib_cmp/j13wsf: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/j13wsf.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/j13wsf.out"
}

@test "3tlib_cmp/oxcalhem: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/oxcalhem.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/oxcalhem.out"
}

@test "3tlib_cmp/ph4hcl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/ph4hcl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/ph4hcl.out"
}

@test "3tlib_cmp/quenchfl: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/quenchfl.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/quenchfl.out"
}

@test "3tlib_cmp/rwpar: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/rwpar.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/rwpar.out"
}

@test "3tlib_cmp/rwssdiag: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/rwssdiag.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/rwssdiag.out"
}

@test "3tlib_cmp/rwtst: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/rwtst.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/rwtst.out"
}

@test "3tlib_cmp/sio2: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/sio2.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/sio2.out"
}

@test "3tlib_cmp/sw2vxch: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/sw2vxch.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/sw2vxch.out"
}

@test "3tlib_cmp/swauto: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swauto.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swauto.out"
}

@test "3tlib_cmp/swbasw: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swbasw.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swbasw.out"
}

@test "3tlib_cmp/swcaarag: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swcaarag.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swcaarag.out"
}

@test "3tlib_cmp/swco2: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swco2.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swco2.out"
}

@test "3tlib_cmp/swg1sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swg1sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swg1sx.out"
}

@test "3tlib_cmp/swgeo: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swgeo.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swgeo.out"
}

@test "3tlib_cmp/swmaj: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swmaj.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swmaj.out"
}

@test "3tlib_cmp/swmajd: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swmajd.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swmajd.out"
}

@test "3tlib_cmp/swmjdofe: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swmjdofe.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swmjdofe.out"
}

@test "3tlib_cmp/swpar: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swpar.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swpar.out"
}

@test "3tlib_cmp/swpharag: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swpharag.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swpharag.out"
}

@test "3tlib_cmp/swrdxcp: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swrdxcp.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swrdxcp.out"
}

@test "3tlib_cmp/swtst: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swtst.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swtst.out"
}

@test "3tlib_cmp/swv1sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swv1sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swv1sx.out"
}

@test "3tlib_cmp/swv1sxca: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swv1sxca.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swv1sxca.out"
}

@test "3tlib_cmp/swv2sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/3tlib_cmp/swv2sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "$REPO_ROOT/tests/testlib/expected/3tlib_cmp/swv2sx.out"
}

