#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" ypf; }
teardown() { teardown_workdir; }

@test "6tlib_ypf/calhal90: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ypf/calhal90.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ypf/calhal90.out"
}

@test "6tlib_ypf/evapsw60: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ypf/evapsw60.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ypf/evapsw60.out"
}

