#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" com; }
teardown() { teardown_workdir; }

@test "6tlib_cmp/crisqtz: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/crisqtz.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/crisqtz.out"
}

@test "6tlib_cmp/dedolo: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/dedolo.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/dedolo.out"
}

@test "6tlib_cmp/heatqf: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/heatqf.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/heatqf.out"
}

@test "6tlib_cmp/heatsw: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/heatsw.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/heatsw.out"
}

@test "6tlib_cmp/heatswfl: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/heatswfl.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/heatswfl.out"
}

@test "6tlib_cmp/j13wsf: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/j13wsf.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/j13wsf.out"
}

@test "6tlib_cmp/j13wtitr: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/j13wtitr.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/j13wtitr.out"
}

@test "6tlib_cmp/j13wtuff: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/j13wtuff.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/j13wtuff.out"
}

@test "6tlib_cmp/methane: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/methane.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/methane.out"
}

@test "6tlib_cmp/micro: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/micro.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/micro.out"
}

@test "6tlib_cmp/microft: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/microft.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/microft.out"
}

@test "6tlib_cmp/pptcal: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/pptcal.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/pptcal.out"
}

@test "6tlib_cmp/pptmins: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/pptmins.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/pptmins.out"
}

@test "6tlib_cmp/pptqtz: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/pptqtz.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/pptqtz.out"
}

@test "6tlib_cmp/pptqtza: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/pptqtza.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/pptqtza.out"
}

@test "6tlib_cmp/pyrsw: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/pyrsw.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/pyrsw.out"
}

@test "6tlib_cmp/rwssdiag: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/rwssdiag.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/rwssdiag.out"
}

@test "6tlib_cmp/rwtitr: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/rwtitr.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/rwtitr.out"
}

@test "6tlib_cmp/swtitr: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/swtitr.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/swtitr.out"
}

@test "6tlib_cmp/swxrca: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/swxrca.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/swxrca.out"
}

@test "6tlib_cmp/swxrcaft: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_cmp/swxrcaft.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_cmp/swxrcaft.out"
}

