#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" hmw; }
teardown() { teardown_workdir; }

@test "6tlib_hmw/calhal: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_hmw/calhal.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_hmw/calhal.out"
}

@test "6tlib_hmw/evapsw: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_hmw/evapsw.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_hmw/evapsw.out"
}

@test "6tlib_hmw/evswgyha: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_hmw/evswgyha.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_hmw/evswgyha.out"
}

@test "6tlib_hmw/fwbrmix: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_hmw/fwbrmix.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_hmw/fwbrmix.out"
}

@test "6tlib_hmw/gypanhy: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_hmw/gypanhy.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_hmw/gypanhy.out"
}

@test "6tlib_hmw/mgso4: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_hmw/mgso4.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_hmw/mgso4.out"
}

@test "6tlib_hmw/swv1sxk: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_hmw/swv1sxk.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_hmw/swv1sxk.out"
}

