#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" fmt; }
teardown() { teardown_workdir; }

@test "6tlib_fmt/c4pgwbN2: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_fmt/c4pgwbN2.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_fmt/c4pgwbN2.out"
}

@test "6tlib_fmt/f24vc7b3: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_fmt/f24vc7b3.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_fmt/f24vc7b3.out"
}

@test "6tlib_fmt/f24vc7k4: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_fmt/f24vc7k4.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_fmt/f24vc7k4.out"
}

@test "6tlib_fmt/f24vc7m: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_fmt/f24vc7m.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_fmt/f24vc7m.out"
}

@test "6tlib_fmt/gypnaclx: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_fmt/gypnaclx.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_fmt/gypnaclx.out"
}

