#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" ymp; }
teardown() { teardown_workdir; }

@test "6tlib_ymp/crisqtz: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/crisqtz.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/crisqtz.out"
}

@test "6tlib_ymp/dedolo: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/dedolo.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/dedolo.out"
}

@test "6tlib_ymp/heatqf: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/heatqf.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/heatqf.out"
}

@test "6tlib_ymp/heatsw: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/heatsw.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/heatsw.out"
}

@test "6tlib_ymp/heatswfl: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/heatswfl.6i"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/heatswfl.out"
}

@test "6tlib_ymp/j13wsf: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/j13wsf.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/j13wsf.out"
}

@test "6tlib_ymp/j13wtitr: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/j13wtitr.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/j13wtitr.out"
}

@test "6tlib_ymp/j13wtuff: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/j13wtuff.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/j13wtuff.out"
}

@test "6tlib_ymp/methane: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/methane.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/methane.out"
}

@test "6tlib_ymp/micro: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/micro.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/micro.out"
}

@test "6tlib_ymp/microft: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/microft.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/microft.out"
}

@test "6tlib_ymp/pptcal: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/pptcal.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/pptcal.out"
}

@test "6tlib_ymp/pptmins: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/pptmins.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/pptmins.out"
}

@test "6tlib_ymp/pptqtz: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/pptqtz.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/pptqtz.out"
}

@test "6tlib_ymp/pptqtza: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/pptqtza.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/pptqtza.out"
}

@test "6tlib_ymp/pyrsw: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/pyrsw.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/pyrsw.out"
}

@test "6tlib_ymp/rwssdiag: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/rwssdiag.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/rwssdiag.out"
}

@test "6tlib_ymp/rwtitr: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/rwtitr.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/rwtitr.out"
}

@test "6tlib_ymp/swtitr: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/swtitr.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/swtitr.out"
}

@test "6tlib_ymp/swxrca: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/swxrca.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/swxrca.out"
}

@test "6tlib_ymp/swxrcaft: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/6tlib_ymp/swxrcaft.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "6tlib_ymp/swxrcaft.out"
}

