#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" com; }
teardown() { teardown_workdir; }

@test "xchtlib/swv1sxk: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swv1sxk.6i"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swv1sxk.6i.out"
}

@test "xchtlib/swxrca: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swxrca.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swxrca.6i.out"
}

@test "xchtlib/swxrcaft: output matches reference" {
    run_eq6 "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swxrcaft.6i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swxrcaft.6i.out"
}

