#!/usr/bin/env bats
# Auto-generated by make regen-testlib-refs — do not edit by hand.
load '../../lib/helpers'

setup()    { setup_workdir; stage_data1_for "$WORKDIR" com; }
teardown() { teardown_workdir; }

@test "xchtlib/sw2vxch: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/sw2vxch.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/sw2vxch.3i.out"
}

@test "xchtlib/swg1sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swg1sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swg1sx.3i.out"
}

@test "xchtlib/swv1sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swv1sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swv1sx.3i.out"
}

@test "xchtlib/swv1sxca: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swv1sxca.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swv1sxca.3i.out"
}

@test "xchtlib/swv1sxk: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swv1sxk.3i"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swv1sxk.3i.out"
}

@test "xchtlib/swv2sx: output matches reference" {
    run_eq3nr "$WORKDIR" "$REPO_ROOT/tests/testlib/inputs/xchtlib/swv2sx.3i"
    assert_match "Normal exit" "$WORKDIR/output"
    assert_output_matches_ref "$WORKDIR/output" \
        "xchtlib/swv2sx.3i.out"
}

