#!/usr/bin/env python3
"""
Generate sources.mk — static source file lists for the v8.0a Makefile.

Run via:  make regen-sources
          make check-sources

Must be invoked from the repo root after 'make extract' has populated src/.
"""
import os
import subprocess
import sys


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_BASE = os.path.join(REPO_ROOT, "src")

# EQ6 Fortran module sources that must compile before all other EQ6 files.
EQ6_MODULES = {"mod6pt.f", "mod6xf.f"}

# Ordered list of (make_variable, src_subpath) pairs.
# EQ6 is split into two entries to preserve the module-first constraint.
COMPONENTS = [
    ("EQLIBU_SRCS",      "eqlibu/src"),
    ("EQLIBG_SRCS",      "eqlibg/src"),
    ("EQLIB_SRCS",       "eqlib/src"),
    ("EQ3NR_SRCS",       "eq3nr/src"),
    ("EQ6_MODULE_SRCS",  "eq6/src"),   # only mod6pt.f + mod6xf.f
    ("EQ6_OTHER_SRCS",   "eq6/src"),   # everything else in eq6/src
    ("EQPT_SRCS",        "eqpt/src"),
    ("XCON3_SRCS",       "xcon3/src"),
    ("XCON6_SRCS",       "xcon6/src"),
]


def upstream_commit():
    try:
        result = subprocess.run(
            ["git", "-C", REPO_ROOT, "submodule", "status", "upstream"],
            capture_output=True, text=True, check=True,
        )
        # Output format: " <hash> upstream (<describe>)"
        return result.stdout.strip().lstrip("+-").split()[0]
    except Exception:
        return "unknown"


def list_files(subpath, only=None, exclude=None):
    d = os.path.join(SRC_BASE, subpath)
    if not os.path.isdir(d):
        print(f"ERROR: {d} does not exist. Run 'make extract' first.", file=sys.stderr)
        sys.exit(1)
    files = sorted(f for f in os.listdir(d) if f.endswith(".f"))
    if only is not None:
        files = [f for f in files if f in only]
    if exclude is not None:
        files = [f for f in files if f not in exclude]
    return files


def format_var(name, files):
    if not files:
        return f"{name} ="
    lines = [f"{name} = \\"]
    for i, f in enumerate(files):
        suffix = " \\" if i < len(files) - 1 else ""
        lines.append(f"    {f}{suffix}")
    return "\n".join(lines)


def main():
    commit = upstream_commit()
    out = []
    out.append("# Generated by 'make regen-sources'. Commit alongside submodule pointer updates.")
    out.append(f"# Pinned to upstream submodule commit: {commit}")
    out.append("")

    for var, subpath in COMPONENTS:
        if var == "EQ6_MODULE_SRCS":
            files = list_files(subpath, only=EQ6_MODULES)
            out.append("# EQ6: modules must compile first (define Fortran .mod files consumed by EQ6_OTHER_SRCS)")
        elif var == "EQ6_OTHER_SRCS":
            files = list_files(subpath, exclude=EQ6_MODULES)
        else:
            files = list_files(subpath)
        out.append(format_var(var, files))
        out.append("")

    print("\n".join(out).rstrip() + "\n")


if __name__ == "__main__":
    main()
