#!/usr/bin/env bash
# Regenerate testlib reference outputs and BATS test files for the current platform.
# Run via: make regen-testlib-refs
# Commit the results in tests/testlib/expected/<platform>/ and tests/cases/testlib/.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="$REPO_ROOT/bin"
DATA1_CACHE="$REPO_ROOT/tests/.data1_cache"
INPUTS="$REPO_ROOT/tests/testlib/inputs"
CASES="$REPO_ROOT/tests/cases/testlib"

# Canonical platform tag: 'linux' or 'mac'.
case "$(uname -s)" in
    Darwin) PLATFORM=mac ;;
    *)      PLATFORM=linux ;;
esac
EXPECTED="$REPO_ROOT/tests/testlib/expected/$PLATFORM"

echo "==> Platform: $PLATFORM  (writing to tests/testlib/expected/$PLATFORM/)"

strip_timing() {
    grep -v \
        -e '^ Run  [0-9][0-9]:[0-9][0-9]:[0-9][0-9]' \
        -e '^          Start time = ' \
        -e '^            End time = ' \
        -e '^           Run time = ' \
        "$1"
}

run_case() {
    local exe="$1"       # eq3nr or eq6
    local data1="$2"     # path to data1 file
    local input="$3"     # path to .3i or .6i input
    local outfile="$4"   # destination .out reference file

    local tmpdir
    tmpdir=$(mktemp -d)
    cp "$data1"  "$tmpdir/data1"
    cp "$input"  "$tmpdir/input"
    (cd "$tmpdir" && "$BIN/$exe" > run.log 2>&1) || {
        echo "  FAILED (exe error): $exe on $(basename "$input")" >&2
        cat "$tmpdir/run.log" >&2
        rm -rf "$tmpdir"
        return 1
    }
    if ! grep -q "Normal exit" "$tmpdir/output"; then
        echo "  WARNING: no Normal exit — $(basename "$input") (non-converging case, still writing reference)" >&2
    fi
    mkdir -p "$(dirname "$outfile")"
    strip_timing "$tmpdir/output" > "$outfile"
    rm -rf "$tmpdir"
}

# gen_bats_file lib exe dataset ext [outname] [ref_suffix]
#   lib        — input directory under tests/testlib/inputs/ (e.g. 3tlib_cmp)
#   exe        — eq3nr or eq6
#   dataset    — data1 cache suffix (e.g. com, fmt, hmw, ymp, ypf)
#   ext        — input file extension (3i or 6i)
#   outname    — (optional) BATS file basename; defaults to $lib
#   ref_suffix — (optional) suffix inserted before .out in the reference path;
#                used when the same base name exists for both .3i and .6i inputs
#                (e.g. ".3i" → ref path becomes lib/base.3i.out)
gen_bats_file() {
    local lib="$1"
    local exe="$2"
    local dataset="$3"
    local ext="$4"
    local outname="${5:-$lib}"
    local ref_suffix="${6:-}"
    local outfile="$CASES/${outname}.bats"
    {
        echo "#!/usr/bin/env bats"
        echo "# Auto-generated by make regen-testlib-refs — do not edit by hand."
        echo "load '../../lib/helpers'"
        echo ""
        echo "setup()    { setup_workdir; stage_data1_for \"\$WORKDIR\" ${dataset}; }"
        echo "teardown() { teardown_workdir; }"
        echo ""

        for input in "$INPUTS/$lib/"*."$ext"; do
            [ -f "$input" ] || continue
            local base
            base=$(basename "$input" ".$ext")
            local ref="$EXPECTED/$lib/${base}${ref_suffix}.out"
            echo "@test \"${lib}/${base}: output matches reference\" {"
            echo "    run_${exe/-/_} \"\$WORKDIR\" \"\$REPO_ROOT/tests/testlib/inputs/${lib}/${base}.${ext}\""
            # Only assert Normal exit for cases that actually reach it (some EQ6 runs are
            # known non-converging; the upstream reference itself lacks Normal exit).
            if grep -q "Normal exit" "$ref" 2>/dev/null; then
                echo "    assert_match \"Normal exit\" \"\$WORKDIR/output\""
            fi
            echo "    assert_output_matches_ref \"\$WORKDIR/output\" \\"
            echo "        \"${lib}/${base}${ref_suffix}.out\""
            echo "}"
            echo ""
        done
    } > "$outfile"
}

mkdir -p "$CASES"

echo "==> Generating 3tlib_cmp reference outputs (41 cases) ..."
for input in "$INPUTS/3tlib_cmp/"*.3i; do
    base=$(basename "$input" .3i)
    echo "    $base"
    run_case eq3nr "$DATA1_CACHE/data1.com" "$input" "$EXPECTED/3tlib_cmp/$base.out"
done
gen_bats_file 3tlib_cmp eq3nr com 3i
echo "    => tests/cases/testlib/3tlib_cmp.bats"

echo "==> Generating 6tlib_cmp reference outputs (21 cases) ..."
for input in "$INPUTS/6tlib_cmp/"*.6i; do
    base=$(basename "$input" .6i)
    echo "    $base"
    run_case eq6 "$DATA1_CACHE/data1.com" "$input" "$EXPECTED/6tlib_cmp/$base.out"
done
gen_bats_file 6tlib_cmp eq6 com 6i
echo "    => tests/cases/testlib/6tlib_cmp.bats"

echo "==> Generating 3tlib_fmt reference outputs (7 cases) ..."
for input in "$INPUTS/3tlib_fmt/"*.3i; do
    base=$(basename "$input" .3i)
    echo "    $base"
    run_case eq3nr "$DATA1_CACHE/data1.fmt" "$input" "$EXPECTED/3tlib_fmt/$base.out"
done
gen_bats_file 3tlib_fmt eq3nr fmt 3i
echo "    => tests/cases/testlib/3tlib_fmt.bats"

echo "==> Generating 6tlib_fmt reference outputs (5 cases) ..."
for input in "$INPUTS/6tlib_fmt/"*.6i; do
    base=$(basename "$input" .6i)
    echo "    $base"
    run_case eq6 "$DATA1_CACHE/data1.fmt" "$input" "$EXPECTED/6tlib_fmt/$base.out"
done
gen_bats_file 6tlib_fmt eq6 fmt 6i
echo "    => tests/cases/testlib/6tlib_fmt.bats"

echo "==> Generating 3tlib_hmw reference outputs (9 cases) ..."
for input in "$INPUTS/3tlib_hmw/"*.3i; do
    base=$(basename "$input" .3i)
    echo "    $base"
    run_case eq3nr "$DATA1_CACHE/data1.hmw" "$input" "$EXPECTED/3tlib_hmw/$base.out"
done
gen_bats_file 3tlib_hmw eq3nr hmw 3i
echo "    => tests/cases/testlib/3tlib_hmw.bats"

echo "==> Generating 6tlib_hmw reference outputs (7 cases) ..."
for input in "$INPUTS/6tlib_hmw/"*.6i; do
    base=$(basename "$input" .6i)
    echo "    $base"
    run_case eq6 "$DATA1_CACHE/data1.hmw" "$input" "$EXPECTED/6tlib_hmw/$base.out"
done
gen_bats_file 6tlib_hmw eq6 hmw 6i
echo "    => tests/cases/testlib/6tlib_hmw.bats"

echo "==> Generating 3tlib_ymp reference outputs (41 cases) ..."
for input in "$INPUTS/3tlib_ymp/"*.3i; do
    base=$(basename "$input" .3i)
    echo "    $base"
    run_case eq3nr "$DATA1_CACHE/data1.ymp" "$input" "$EXPECTED/3tlib_ymp/$base.out"
done
gen_bats_file 3tlib_ymp eq3nr ymp 3i
echo "    => tests/cases/testlib/3tlib_ymp.bats"

echo "==> Generating 6tlib_ymp reference outputs (21 cases) ..."
for input in "$INPUTS/6tlib_ymp/"*.6i; do
    base=$(basename "$input" .6i)
    echo "    $base"
    run_case eq6 "$DATA1_CACHE/data1.ymp" "$input" "$EXPECTED/6tlib_ymp/$base.out"
done
gen_bats_file 6tlib_ymp eq6 ymp 6i
echo "    => tests/cases/testlib/6tlib_ymp.bats"

echo "==> Generating 3tlib_ypf reference outputs (7 cases) ..."
for input in "$INPUTS/3tlib_ypf/"*.3i; do
    base=$(basename "$input" .3i)
    echo "    $base"
    run_case eq3nr "$DATA1_CACHE/data1.ypf" "$input" "$EXPECTED/3tlib_ypf/$base.out"
done
gen_bats_file 3tlib_ypf eq3nr ypf 3i
echo "    => tests/cases/testlib/3tlib_ypf.bats"

echo "==> Generating 6tlib_ypf reference outputs (2 cases) ..."
for input in "$INPUTS/6tlib_ypf/"*.6i; do
    base=$(basename "$input" .6i)
    echo "    $base"
    run_case eq6 "$DATA1_CACHE/data1.ypf" "$input" "$EXPECTED/6tlib_ypf/$base.out"
done
gen_bats_file 6tlib_ypf eq6 ypf 6i
echo "    => tests/cases/testlib/6tlib_ypf.bats"

# xchtlib has both .3i and .6i inputs — one case (swv1sxk) exists in both.
# Reference files use the input extension as a suffix (e.g. swv1sxk.3i.out) to
# keep them distinct when the base name is shared across executables.
echo "==> Generating xchtlib reference outputs (9 cases: 6 eq3nr + 3 eq6) ..."
for input in "$INPUTS/xchtlib/"*.3i; do
    base=$(basename "$input" .3i)
    echo "    (eq3nr) $base"
    run_case eq3nr "$DATA1_CACHE/data1.com" "$input" "$EXPECTED/xchtlib/$base.3i.out"
done
for input in "$INPUTS/xchtlib/"*.6i; do
    base=$(basename "$input" .6i)
    echo "    (eq6)   $base"
    run_case eq6 "$DATA1_CACHE/data1.com" "$input" "$EXPECTED/xchtlib/$base.6i.out"
done
gen_bats_file xchtlib eq3nr com 3i xchtlib_eq3nr .3i
gen_bats_file xchtlib eq6   com 6i xchtlib_eq6   .6i
echo "    => tests/cases/testlib/xchtlib_eq3nr.bats"
echo "    => tests/cases/testlib/xchtlib_eq6.bats"

echo "==> Done. Commit tests/testlib/expected/$PLATFORM/ and tests/cases/testlib/."
