#!/usr/bin/env bash
# Regenerate testlib reference outputs and BATS test files.
# Run via: make regen-testlib-refs
# Commit the results in tests/testlib/expected/ and tests/cases/testlib/.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BIN="$REPO_ROOT/bin"
DATA1_CACHE="$REPO_ROOT/tests/.data1_cache"
INPUTS="$REPO_ROOT/tests/testlib/inputs"
EXPECTED="$REPO_ROOT/tests/testlib/expected"
CASES="$REPO_ROOT/tests/cases/testlib"

strip_timing() {
    grep -v \
        -e '^ Run  [0-9][0-9]:[0-9][0-9]:[0-9][0-9]' \
        -e '^          Start time = ' \
        -e '^            End time = ' \
        -e '^           Run time = ' \
        "$1"
}

run_case() {
    local exe="$1"       # eq3nr or eq6
    local data1="$2"     # path to data1 file
    local input="$3"     # path to .3i or .6i input
    local outfile="$4"   # destination .out reference file

    local tmpdir
    tmpdir=$(mktemp -d)
    cp "$data1"  "$tmpdir/data1"
    cp "$input"  "$tmpdir/input"
    (cd "$tmpdir" && "$BIN/$exe" > run.log 2>&1) || {
        echo "  FAILED: $exe on $(basename "$input")" >&2
        cat "$tmpdir/run.log" >&2
        rm -rf "$tmpdir"
        return 1
    }
    if ! grep -q "Normal exit" "$tmpdir/output"; then
        echo "  NO NORMAL EXIT: $exe on $(basename "$input")" >&2
        tail -5 "$tmpdir/output" >&2
        rm -rf "$tmpdir"
        return 1
    fi
    mkdir -p "$(dirname "$outfile")"
    strip_timing "$tmpdir/output" > "$outfile"
    rm -rf "$tmpdir"
}

gen_bats_file() {
    local lib="$1"       # e.g. 3tlib_cmp
    local exe="$2"       # eq3nr or eq6
    local dataset="$3"   # e.g. com
    local ext="$4"       # 3i or 6i
    local outfile="$CASES/${lib}.bats"
    {
        echo "#!/usr/bin/env bats"
        echo "# Auto-generated by make regen-testlib-refs — do not edit by hand."
        echo "load '../../lib/helpers'"
        echo ""
        echo "setup()    { setup_workdir; stage_data1_for \"\$WORKDIR\" ${dataset}; }"
        echo "teardown() { teardown_workdir; }"
        echo ""

        for input in "$INPUTS/$lib/"*."$ext"; do
            [ -f "$input" ] || continue
            local base
            base=$(basename "$input" ".$ext")
            echo "@test \"${lib}/${base}: output matches reference\" {"
            echo "    run_${exe/-/_} \"\$WORKDIR\" \"\$REPO_ROOT/tests/testlib/inputs/${lib}/${base}.${ext}\""
            echo "    assert_match \"Normal exit\" \"\$WORKDIR/output\""
            echo "    assert_output_matches_ref \"\$WORKDIR/output\" \\"
            echo "        \"\$REPO_ROOT/tests/testlib/expected/${lib}/${base}.out\""
            echo "}"
            echo ""
        done
    } > "$outfile"
}

mkdir -p "$CASES"

echo "==> Generating 3tlib_cmp reference outputs (41 cases) ..."
for input in "$INPUTS/3tlib_cmp/"*.3i; do
    base=$(basename "$input" .3i)
    echo "    $base"
    run_case eq3nr "$DATA1_CACHE/data1.com" "$input" "$EXPECTED/3tlib_cmp/$base.out"
done
gen_bats_file 3tlib_cmp eq3nr com 3i
echo "    => tests/cases/testlib/3tlib_cmp.bats"

echo "==> Generating 6tlib_cmp reference outputs (21 cases) ..."
for input in "$INPUTS/6tlib_cmp/"*.6i; do
    base=$(basename "$input" .6i)
    echo "    $base"
    run_case eq6 "$DATA1_CACHE/data1.com" "$input" "$EXPECTED/6tlib_cmp/$base.out"
done
gen_bats_file 6tlib_cmp eq6 com 6i
echo "    => tests/cases/testlib/6tlib_cmp.bats"

echo "==> Done. Commit tests/testlib/expected/ and tests/cases/testlib/."
